In [22]:
!apt-get update && apt-get install -y build-essential

!pip install torchmetrics
!pip install cmdstanpy==1.2.5
!pip uninstall prophet -y
!pip install prophet==1.1.4

Get:1 http://security.ubuntu.com/ubuntu jammy-security InRelease [129 kB]
Get:2 https://cli.github.com/packages stable InRelease [3,917 B]
Hit:3 http://archive.ubuntu.com/ubuntu jammy InRelease
Get:4 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [128 kB]
Get:5 https://r2u.stat.illinois.edu/ubuntu jammy InRelease [6,555 B]
Get:6 https://cli.github.com/packages stable/main amd64 Packages [356 B]
Get:7 http://archive.ubuntu.com/ubuntu jammy-backports InRelease [127 kB]
Get:8 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease [3,632 B]
Get:9 http://security.ubuntu.com/ubuntu jammy-security/restricted amd64 Packages [7,479 kB]
Get:10 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease [18.1 kB]
Get:11 http://security.ubuntu.com/ubuntu jammy-security/multiverse amd64 Packages [84.1 kB]
Get:12 http://security.ubuntu.com/ubuntu jammy-security/main amd64 Packages [4,155 kB]
Hit:13 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Get:14 http://security.ubuntu.com/ubuntu jammy-security/universe amd64 Packages [1,314 kB]
Get:15 https://r2u.stat.illinois.edu/ubuntu jammy/main amd64 Packages [3,144 kB]
Get:16 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages [4,488 kB]
Get:17 https://r2u.stat.illinois.edu/ubuntu jammy/main all Packages [10.6 MB]
Get:18 http://archive.ubuntu.com/ubuntu jammy-updates/multiverse amd64 Packages [92.7 kB]
Get:19 http://archive.ubuntu.com/ubuntu jammy-updates/restricted amd64 Packages [7,770 kB]
Get:20 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 Packages [1,616 kB]
Get:21 http://archive.ubuntu.com/ubuntu jammy-backports/universe amd64 Packages [35.6 kB]
Get:22 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ Packages [102 kB]
Get:23 http://archive.ubuntu.com/ubuntu jammy-backports/main amd64 Packages [82.8 kB]
Get:24 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy/main amd64 Packages [43.4 kB]
Fetched 41.5 MB in 4s (11.7 MB/s)
Reading package lists... Done
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
build-essential is already the newest version (12.9ubuntu3).
0 upgraded, 0 newly installed, 0 to remove and 131 not upgraded.
Requirement already satisfied: torchmetrics in /usr/local/lib/python3.12/dist-packages (1.9.0)
Requirement already satisfied: numpy>1.20.0 in /usr/local/lib/python3.12/dist-packages (from torchmetrics) (2.0.2)
Requirement already satisfied: packaging>17.1 in /usr/local/lib/python3.12/dist-packages (from torchmetrics) (26.2)
Requirement already satisfied: torch>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from torchmetrics) (2.11.0+cpu)
Requirement already satisfied: lightning-utilities>=0.15.3 in /usr/local/lib/python3.12/dist-packages (from torchmetrics) (0.15.3)
Requirement already satisfied: typing_extensions in /usr/local/lib/python3.12/dist-packages (from lightning-utilities>=0.15.3->torchmetrics) (4.16.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->torchmetrics) (3.29.7)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->torchmetrics) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->torchmetrics) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->torchmetrics) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->torchmetrics) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->torchmetrics) (2025.3.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=2.0.0->torchmetrics) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=2.0.0->torchmetrics) (3.0.3)
Collecting cmdstanpy==1.2.5
  Downloading cmdstanpy-1.2.5-py3-none-any.whl.metadata (4.0 kB)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from cmdstanpy==1.2.5) (2.2.2)
Requirement already satisfied: numpy>=1.21 in /usr/local/lib/python3.12/dist-packages (from cmdstanpy==1.2.5) (2.0.2)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from cmdstanpy==1.2.5) (4.67.3)
Requirement already satisfied: stanio<2.0.0,>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from cmdstanpy==1.2.5) (0.5.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->cmdstanpy==1.2.5) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->cmdstanpy==1.2.5) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->cmdstanpy==1.2.5) (2026.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->cmdstanpy==1.2.5) (1.17.0)
Downloading cmdstanpy-1.2.5-py3-none-any.whl (94 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 94.5/94.5 kB 6.3 MB/s eta 0:00:00
Installing collected packages: cmdstanpy
  Attempting uninstall: cmdstanpy
    Found existing installation: cmdstanpy 1.3.0
    Uninstalling cmdstanpy-1.3.0:
      Successfully uninstalled cmdstanpy-1.3.0
Successfully installed cmdstanpy-1.2.5

Found existing installation: prophet 1.3.0
Uninstalling prophet-1.3.0:
  Successfully uninstalled prophet-1.3.0
Collecting prophet==1.1.4
  Downloading prophet-1.1.4-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.6 kB)
Requirement already satisfied: cmdstanpy>=1.0.4 in /usr/local/lib/python3.12/dist-packages (from prophet==1.1.4) (1.2.5)
Requirement already satisfied: numpy>=1.15.4 in /usr/local/lib/python3.12/dist-packages (from prophet==1.1.4) (2.0.2)
Requirement already satisfied: matplotlib>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from prophet==1.1.4) (3.10.0)
Requirement already satisfied: pandas>=1.0.4 in /usr/local/lib/python3.12/dist-packages (from prophet==1.1.4) (2.2.2)
Collecting LunarCalendar>=0.0.9 (from prophet==1.1.4)
  Downloading LunarCalendar-0.0.9-py2.py3-none-any.whl.metadata (6.3 kB)
Collecting convertdate>=2.1.2 (from prophet==1.1.4)
  Downloading convertdate-2.4.1-py3-none-any.whl.metadata (9.7 kB)
Requirement already satisfied: holidays>=0.25 in /usr/local/lib/python3.12/dist-packages (from prophet==1.1.4) (0.100)
Requirement already satisfied: python-dateutil>=2.8.0 in /usr/local/lib/python3.12/dist-packages (from prophet==1.1.4) (2.9.0.post0)
Requirement already satisfied: tqdm>=4.36.1 in /usr/local/lib/python3.12/dist-packages (from prophet==1.1.4) (4.67.3)
Requirement already satisfied: importlib-resources in /usr/local/lib/python3.12/dist-packages (from prophet==1.1.4) (7.1.0)
Requirement already satisfied: stanio<2.0.0,>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from cmdstanpy>=1.0.4->prophet==1.1.4) (0.5.1)
Collecting pymeeus<=1,>=0.3.13 (from convertdate>=2.1.2->prophet==1.1.4)
  Downloading PyMeeus-0.5.12.tar.gz (5.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.8/5.8 MB 52.7 MB/s eta 0:00:0000:0100:01
  Preparing metadata (setup.py) ... done
Collecting ephem>=3.7.5.3 (from LunarCalendar>=0.0.9->prophet==1.1.4)
  Downloading ephem-4.2.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (6.3 kB)
Requirement already satisfied: pytz in /usr/local/lib/python3.12/dist-packages (from LunarCalendar>=0.0.9->prophet==1.1.4) (2025.2)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=2.0.0->prophet==1.1.4) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=2.0.0->prophet==1.1.4) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=2.0.0->prophet==1.1.4) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=2.0.0->prophet==1.1.4) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=2.0.0->prophet==1.1.4) (26.2)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=2.0.0->prophet==1.1.4) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=2.0.0->prophet==1.1.4) (3.3.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.4->prophet==1.1.4) (2026.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.0->prophet==1.1.4) (1.17.0)
Downloading prophet-1.1.4-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (13.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.0/13.0 MB 97.5 MB/s eta 0:00:00:00:010:01
Downloading convertdate-2.4.1-py3-none-any.whl (48 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 48.4/48.4 kB 3.2 MB/s eta 0:00:00
Downloading LunarCalendar-0.0.9-py2.py3-none-any.whl (18 kB)
Downloading ephem-4.2.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (1.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 64.2 MB/s eta 0:00:00
Building wheels for collected packages: pymeeus
  Building wheel for pymeeus (setup.py) ... done
  Created wheel for pymeeus: filename=PyMeeus-0.5.12-py3-none-any.whl size=732000 sha256=ed3497226786a5aea0eb73e6f8cb2866cf10742e9f978eee696a84a9934e0c60
  Stored in directory: /root/.cache/pip/wheels/92/74/5d/5cf1193a619dc315b5b0a158876900e21440c71130251307b6
Successfully built pymeeus
Installing collected packages: pymeeus, ephem, convertdate, LunarCalendar, prophet
Successfully installed LunarCalendar-0.0.9 convertdate-2.4.1 ephem-4.2.1 prophet-1.1.4 pymeeus-0.5.12

In [23]:
import pandas as pd
import numpy as np
import torch
from prophet import Prophet
from torchmetrics import WeightedMeanAbsolutePercentageError
from sklearn.metrics import mean_absolute_error, mean_squared_error

In [24]:
%cd /content/Walmart_sales_forecasting
data_dir = 'data/processed/feature_engineering.feather'
df_feature = pd.read_feather(data_dir)
df_feature

/content/Walmart_sales_forecasting

,Store,Dept,Date,Weekly_Sales,Type,Size,Temperature,Fuel_Price,MarkDown1,MarkDown2,...,mean_sales_last_6_week,max_sales_last_6_week,min_sales_last_6_week,std_sales_last_6_week,emw_sales_0.5,emw_sales_0.75,sum_store_1_week,mean_store_1_week,sum_dept_1_week,mean_dept_1_week
6,1,1,2010-03-19,22136.64,A,151315,54.58,2.720,0.00,0.00,...,30360.018333,63593.12,7612.03,26384.953473,20940.430630,15246.700822,1242589.35,17258.185417,846686.47,18815.254889
149,1,2,2010-03-19,43615.49,A,151315,54.58,2.720,0.00,0.00,...,32780.786667,63593.12,7612.03,24477.831239,21538.535315,20414.155206,1242589.35,17258.185417,1742919.72,38731.549333
292,1,3,2010-03-19,9001.37,A,151315,54.58,2.720,0.00,0.00,...,29451.181667,61326.35,7612.03,20480.695326,32577.012657,37815.156301,1242589.35,17258.185417,371295.10,8251.002222
435,1,4,2010-03-19,34118.11,A,151315,54.58,2.720,0.00,0.00,...,20730.351667,43615.49,7612.03,14443.999382,20789.191329,16204.816575,1242589.35,17258.185417,1064848.12,23663.291556
578,1,5,2010-03-19,22632.57,A,151315,54.58,2.720,0.00,0.00,...,25148.031667,43615.49,9001.37,13661.565950,27453.650664,29639.786644,1242589.35,17258.185417,1063601.82,24734.926047
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
421012,45,93,2012-10-26,2487.80,B,118221,58.85,3.882,4018.91,58.08,...,17814.415000,54608.75,717.82,20287.128190,35354.118359,45312.322469,760281.43,11347.484030,1049693.34,24992.698571
421146,45,94,2012-10-26,5203.31,B,118221,58.85,3.882,4018.91,58.08,...,18109.411667,54608.75,1689.10,19999.636394,18920.959180,13193.930617,760281.43,11347.484030,1291378.41,29349.509318
421289,45,95,2012-10-26,56017.47,B,118221,58.85,3.882,4018.91,58.08,...,18695.113333,54608.75,2487.80,19466.945450,12062.134590,7200.965154,760281.43,11347.484030,1709432.51,37987.389111
421434,45,97,2012-10-26,6817.48,B,118221,58.85,3.882,4018.91,58.08,...,26666.748333,56017.47,2487.80,23647.747335,34039.802295,43813.343789,760281.43,11347.484030,596563.70,13558.265909
421569,45,98,2012-10-26,1076.80,B,118221,58.85,3.882,4018.91,58.08,...,23577.608333,56017.47,2487.80,25024.343292,20428.641147,16066.445947,760281.43,11347.484030,302469.28,7201.649524

In [25]:
df_feature.info()

<class 'pandas.core.frame.DataFrame'>
Index: 401996 entries, 6 to 421569
Data columns (total 46 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   Store                   401996 non-null  int64
 1   Dept                    401996 non-null  int64
 2   Date                    401996 non-null  datetime64[ns]
 3   Weekly_Sales            401996 non-null  float64
 4   Type                    401996 non-null  object
 5   Size                    401996 non-null  int64
 6   Temperature             401996 non-null  float64
 7   Fuel_Price              401996 non-null  float64
 8   MarkDown1               401996 non-null  float64
 9   MarkDown2               401996 non-null  float64
 10  MarkDown3               401996 non-null  float64
 11  MarkDown4               401996 non-null  float64
 12  MarkDown5               401996 non-null  float64
 13  CPI                     401996 non-null  float64
 14  Unemployment            401996 non-null  float64
 15  is_test                 401996 non-null  bool
 16  total_markdown          401996 non-null  float64
 17  avg_markdown            401996 non-null  float64
 18  max_markdown            401996 non-null  float64
 19  IsHoliday_True          401996 non-null  bool
 20  temp_category_Cool      401996 non-null  bool
 21  temp_category_Warm      401996 non-null  bool
 22  temp_category_Hot       401996 non-null  bool
 23  Type_encoded            401996 non-null  int64
 24  store_dept              401996 non-null  object
 25  lags_2                  401996 non-null  float64
 26  lags_4                  401996 non-null  float64
 27  lags_6                  401996 non-null  float64
 28  mean_sales_last_2_week  401996 non-null  float64
 29  max_sales_last_2_week   401996 non-null  float64
 30  min_sales_last_2_week   401996 non-null  float64
 31  std_sales_last_2_week   401996 non-null  float64
 32  mean_sales_last_4_week  401996 non-null  float64
 33  max_sales_last_4_week   401996 non-null  float64
 34  min_sales_last_4_week   401996 non-null  float64
 35  std_sales_last_4_week   401996 non-null  float64
 36  mean_sales_last_6_week  401996 non-null  float64
 37  max_sales_last_6_week   401996 non-null  float64
 38  min_sales_last_6_week   401996 non-null  float64
 39  std_sales_last_6_week   401996 non-null  float64
 40  emw_sales_0.5           401996 non-null  float64
 41  emw_sales_0.75          401996 non-null  float64
 42  sum_store_1_week        401996 non-null  float64
 43  mean_store_1_week       401996 non-null  float64
 44  sum_dept_1_week         401996 non-null  float64
 45  mean_dept_1_week        401996 non-null  float64
dtypes: bool(5), datetime64[ns](1), float64(34), int64(4), object(2)
memory usage: 130.7+ MB

In [ ]:
from sklearn.preprocessing import StandardScaler

reg_cols = ['Size', 'Temperature', 'Fuel_Price', 'total_markdown', 'avg_markdown', 'max_markdown']
scaler = StandardScaler()
df_feature[reg_cols] = scaler.fit_transform(df_feature[reg_cols])

In [26]:
test = df_feature[df_feature['is_test']]
train = df_feature[~df_feature['is_test']]

prophet_data = df_feature.groupby(['Date', 'store_dept']).agg(
    {
        'Weekly_Sales' : 'sum',
        'Size' : 'first',
        'Type_encoded' : 'first',
        'IsHoliday_True' : 'first',
        'Temperature': 'first',
        'Fuel_Price' : 'first',
        "total_markdown": "first",   
        "avg_markdown": "first",      
        "max_markdown": "first",
    }
).reset_index()

prophet_data

,Date,store_dept,Weekly_Sales,Size,Type_encoded,IsHoliday_True,Temperature,Fuel_Price,total_markdown,avg_markdown,max_markdown
0,2010-03-19,store_10_dept_1,38252.33,126512,2,False,61.46,3.054,0.00,0.000,0.00
1,2010-03-19,store_10_dept_10,49479.06,126512,2,False,61.46,3.054,0.00,0.000,0.00
2,2010-03-19,store_10_dept_11,30518.98,126512,2,False,61.46,3.054,0.00,0.000,0.00
3,2010-03-19,store_10_dept_12,11762.04,126512,2,False,61.46,3.054,0.00,0.000,0.00
4,2010-03-19,store_10_dept_13,65575.03,126512,2,False,61.46,3.054,0.00,0.000,0.00
...,...,...,...,...,...,...,...,...,...,...,...
401991,2012-10-26,store_9_dept_91,914.84,125833,2,False,69.52,3.506,2189.61,437.922,1666.38
401992,2012-10-26,store_9_dept_92,18310.28,125833,2,False,69.52,3.506,2189.61,437.922,1666.38
401993,2012-10-26,store_9_dept_94,233.02,125833,2,False,69.52,3.506,2189.61,437.922,1666.38
401994,2012-10-26,store_9_dept_95,32382.05,125833,2,False,69.52,3.506,2189.61,437.922,1666.38
401995,2012-10-26,store_9_dept_96,4752.25,125833,2,False,69.52,3.506,2189.61,437.922,1666.38

In [ ]:
def build_prophet_model(prophet_data,  test_data):
    min_test_time = test_data['Date'].min()
    max_test_time = test_data['Date'].max()
    
    prophet_model = {}
    prophet_predictions = {}
    prophet_metrics = pd.DataFrame(columns=['combo', 'mae', 'rmae', 'wape'])
    all_real = []
    all_predict = [] 
    
    
    for combination in prophet_data['store_dept'].unique():
        print(f'Build prophet model for {combination}')
        
        combo = prophet_data[prophet_data['store_dept'] == combination]
        combo = combo.rename(columns={'Date':'ds', 'Weekly_Sales' : 'y'}) #prophen require ds and y
        
        combo_train = combo[combo['ds'] < min_test_time]
        combo_test = combo[(combo['ds'] >= min_test_time) & (combo['ds'] <= max_test_time)]
        if combo_train.empty or combo_test.empty:
            print(f'Skip {combination} due to lack of data')
            continue
        
        model = Prophet(daily_seasonality=False,weekly_seasonality=True, yearly_seasonality=True, seasonality_mode='multiplicative', changepoint_prior_scale=0.5)
        
        for reg in [ 'IsHoliday_True', 'Temperature', 'Fuel_Price', 'total_markdown']:
            model.add_regressor(reg)
        
        try:
            model.fit(combo_train)
        except Exception as e:
            print(f'Fail to train {combination} : {e}')
            continue
        
        # test
        future = combo_test[['ds', 'Size', 'Type_encoded', 'IsHoliday_True', 'Temperature', 'Fuel_Price', 'total_markdown', 'avg_markdown', 'max_markdown']]
        forecast = model.predict(future)
        
        forecast = forecast[['ds', 'yhat', 'yhat_upper', 'yhat_lower']].merge(combo_test[['ds', 'y']], on=['ds'])
        
        prophet_model[combination] = model
        prophet_predictions[combination] = forecast
        
        # evaluate
        mae = mean_absolute_error(forecast['y'], forecast['yhat'])
        rmse = np.sqrt(mean_squared_error(forecast['y'], forecast['yhat']))
        wampe_metrics = WeightedMeanAbsolutePercentageError()
        y_pred = torch.tensor(forecast['yhat'].to_numpy(), dtype=torch.float32)
        y = torch.tensor(forecast['y'].to_numpy(), dtype=torch.float32)
        wampe = wampe_metrics(y_pred, y).item()
        
        prophet_metrics[len(prophet_metrics)] = [combo, mae, rmse, wampe]
        
        #overall evaluation
        all_real.extend(forecast['y'])
        all_predict.extend(forecast['yhat'])
        
    
    mean_mae = np.mean(prophet_metrics['mae'])
    mean_rmse = np.mean(prophet_metrics['rmse'])
    ovr_wampe = WeightedMeanAbsolutePercentageError(torch.from_numpy(np.array(all_real)), torch.from_numpy(np.array(all_predict)))
    
    return prophet_model, prophet_predictions, (mean_mae, mean_rmse, ovr_wampe)


prophet_model, prophet_predictions, (mean_mae, mean_rmse, ovr_wampe) = build_prophet_model(prophet_data,  test)

Build prophet model for  store_10_dept_1
Build prophet model for  store_10_dept_10
Build prophet model for  store_10_dept_11
Build prophet model for  store_10_dept_12
Build prophet model for  store_10_dept_13
Build prophet model for  store_10_dept_14
Build prophet model for  store_10_dept_16
Build prophet model for  store_10_dept_17
Build prophet model for  store_10_dept_18
Build prophet model for  store_10_dept_19
Build prophet model for  store_10_dept_2
Build prophet model for  store_10_dept_20
Build prophet model for  store_10_dept_21
Build prophet model for  store_10_dept_22
Build prophet model for  store_10_dept_23
Build prophet model for  store_10_dept_24
Build prophet model for  store_10_dept_25
Build prophet model for  store_10_dept_26
Build prophet model for  store_10_dept_27
Build prophet model for  store_10_dept_28
Build prophet model for  store_10_dept_29
Build prophet model for  store_10_dept_3
Build prophet model for  store_10_dept_30
Build prophet model for  store_10_dept_31
Build prophet model for  store_10_dept_32
Build prophet model for  store_10_dept_33
Build prophet model for  store_10_dept_34
Build prophet model for  store_10_dept_35
Build prophet model for  store_10_dept_36
Build prophet model for  store_10_dept_37
Build prophet model for  store_10_dept_38
Build prophet model for  store_10_dept_4
Build prophet model for  store_10_dept_40
Build prophet model for  store_10_dept_41
Build prophet model for  store_10_dept_42
Build prophet model for  store_10_dept_44
Build prophet model for  store_10_dept_45
Build prophet model for  store_10_dept_46
Build prophet model for  store_10_dept_48
Build prophet model for  store_10_dept_49
Build prophet model for  store_10_dept_5
Build prophet model for  store_10_dept_50
Build prophet model for  store_10_dept_51
Skip  store_10_dept_51 due to lack of data
Build prophet model for  store_10_dept_52
Build prophet model for  store_10_dept_54
Build prophet model for  store_10_dept_55
Build prophet model for  store_10_dept_56
Build prophet model for  store_10_dept_58
Build prophet model for  store_10_dept_59
Build prophet model for  store_10_dept_6
Build prophet model for  store_10_dept_60
Build prophet model for  store_10_dept_67
Build prophet model for  store_10_dept_7
Build prophet model for  store_10_dept_71
Build prophet model for  store_10_dept_72
Build prophet model for  store_10_dept_74
Build prophet model for  store_10_dept_79
Build prophet model for  store_10_dept_8
Build prophet model for  store_10_dept_80
Build prophet model for  store_10_dept_81
Build prophet model for  store_10_dept_82
Build prophet model for  store_10_dept_83
Build prophet model for  store_10_dept_85
Build prophet model for  store_10_dept_87
Build prophet model for  store_10_dept_9
Build prophet model for  store_10_dept_90
Build prophet model for  store_10_dept_91
Build prophet model for  store_10_dept_92
Build prophet model for  store_10_dept_93
Build prophet model for  store_10_dept_94
Build prophet model for  store_10_dept_95
Build prophet model for  store_10_dept_96
Build prophet model for  store_10_dept_97
Build prophet model for  store_10_dept_98

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_11_dept_1
Build prophet model for  store_11_dept_10

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_11_dept_11

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_11_dept_12

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_11_dept_13

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_11_dept_14
Build prophet model for  store_11_dept_16
Build prophet model for  store_11_dept_17
Build prophet model for  store_11_dept_18

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_11_dept_2

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_11_dept_20
Build prophet model for  store_11_dept_21
Build prophet model for  store_11_dept_22
Build prophet model for  store_11_dept_23
Build prophet model for  store_11_dept_24
Build prophet model for  store_11_dept_25
Build prophet model for  store_11_dept_26
Build prophet model for  store_11_dept_27
Build prophet model for  store_11_dept_28
Build prophet model for  store_11_dept_29
Build prophet model for  store_11_dept_3

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_11_dept_30
Build prophet model for  store_11_dept_31
Build prophet model for  store_11_dept_32

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_11_dept_33
Build prophet model for  store_11_dept_34

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_11_dept_35
Build prophet model for  store_11_dept_36
Build prophet model for  store_11_dept_37

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.
ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_11_dept_38

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_11_dept_4

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_11_dept_40

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_11_dept_41
Build prophet model for  store_11_dept_42
Build prophet model for  store_11_dept_44
Build prophet model for  store_11_dept_46

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_11_dept_49

INFO:prophet:n_changepoints greater than number of observations. Using 17.

Build prophet model for  store_11_dept_5
Build prophet model for  store_11_dept_51
Build prophet model for  store_11_dept_52
Build prophet model for  store_11_dept_54
Build prophet model for  store_11_dept_55
Build prophet model for  store_11_dept_56
Build prophet model for  store_11_dept_58
Build prophet model for  store_11_dept_59
Build prophet model for  store_11_dept_6
Build prophet model for  store_11_dept_67

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_11_dept_7
Build prophet model for  store_11_dept_71

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_11_dept_72

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_11_dept_74

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_11_dept_79

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_11_dept_8

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_11_dept_80

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_11_dept_81

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_11_dept_82
Build prophet model for  store_11_dept_83

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_11_dept_85
Build prophet model for  store_11_dept_87

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_11_dept_9

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_11_dept_90

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_11_dept_91

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_11_dept_92

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_11_dept_93

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_11_dept_94

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_11_dept_95

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_11_dept_96

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_11_dept_97
Build prophet model for  store_11_dept_98
Build prophet model for  store_12_dept_1
Build prophet model for  store_12_dept_10
Build prophet model for  store_12_dept_11
Build prophet model for  store_12_dept_12
Build prophet model for  store_12_dept_13
Build prophet model for  store_12_dept_14
Build prophet model for  store_12_dept_16
Build prophet model for  store_12_dept_17
Build prophet model for  store_12_dept_18
Build prophet model for  store_12_dept_19
Build prophet model for  store_12_dept_2
Build prophet model for  store_12_dept_20
Build prophet model for  store_12_dept_21
Build prophet model for  store_12_dept_22
Build prophet model for  store_12_dept_23
Build prophet model for  store_12_dept_24
Build prophet model for  store_12_dept_25
Build prophet model for  store_12_dept_26
Build prophet model for  store_12_dept_27
Build prophet model for  store_12_dept_28
Build prophet model for  store_12_dept_29
Build prophet model for  store_12_dept_3
Build prophet model for  store_12_dept_30
Build prophet model for  store_12_dept_31
Build prophet model for  store_12_dept_32
Build prophet model for  store_12_dept_33
Build prophet model for  store_12_dept_34
Build prophet model for  store_12_dept_35
Build prophet model for  store_12_dept_36
Build prophet model for  store_12_dept_38
Build prophet model for  store_12_dept_4
Build prophet model for  store_12_dept_40
Build prophet model for  store_12_dept_41
Build prophet model for  store_12_dept_42
Build prophet model for  store_12_dept_44
Build prophet model for  store_12_dept_45
Build prophet model for  store_12_dept_46
Build prophet model for  store_12_dept_5
Build prophet model for  store_12_dept_52
Build prophet model for  store_12_dept_54
Build prophet model for  store_12_dept_55
Build prophet model for  store_12_dept_56
Build prophet model for  store_12_dept_58
Build prophet model for  store_12_dept_59
Build prophet model for  store_12_dept_6
Build prophet model for  store_12_dept_60
Build prophet model for  store_12_dept_67
Build prophet model for  store_12_dept_7
Build prophet model for  store_12_dept_71
Build prophet model for  store_12_dept_72
Build prophet model for  store_12_dept_74
Build prophet model for  store_12_dept_79
Build prophet model for  store_12_dept_8
Build prophet model for  store_12_dept_81
Build prophet model for  store_12_dept_82
Build prophet model for  store_12_dept_83
Build prophet model for  store_12_dept_85
Build prophet model for  store_12_dept_87
Build prophet model for  store_12_dept_9
Build prophet model for  store_12_dept_90
Build prophet model for  store_12_dept_91
Build prophet model for  store_12_dept_92
Build prophet model for  store_12_dept_93
Build prophet model for  store_12_dept_94
Build prophet model for  store_12_dept_95
Build prophet model for  store_12_dept_97
Build prophet model for  store_12_dept_98
Build prophet model for  store_13_dept_1

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_13_dept_10

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_13_dept_11

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_13_dept_12

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_13_dept_13
Build prophet model for  store_13_dept_14
Build prophet model for  store_13_dept_16
Build prophet model for  store_13_dept_17
Build prophet model for  store_13_dept_18

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_13_dept_19
Build prophet model for  store_13_dept_2

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_13_dept_20
Build prophet model for  store_13_dept_21
Build prophet model for  store_13_dept_22
Build prophet model for  store_13_dept_23
Build prophet model for  store_13_dept_24
Build prophet model for  store_13_dept_25
Build prophet model for  store_13_dept_26
Build prophet model for  store_13_dept_27
Build prophet model for  store_13_dept_28
Build prophet model for  store_13_dept_29
Build prophet model for  store_13_dept_3

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_13_dept_30
Build prophet model for  store_13_dept_31
Build prophet model for  store_13_dept_32

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_13_dept_33
Build prophet model for  store_13_dept_34

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_13_dept_35

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_13_dept_36
Build prophet model for  store_13_dept_37

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_13_dept_38

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_13_dept_4

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_13_dept_40

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_13_dept_41
Build prophet model for  store_13_dept_42
Build prophet model for  store_13_dept_44
Build prophet model for  store_13_dept_45
Build prophet model for  store_13_dept_46
Build prophet model for  store_13_dept_48

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_13_dept_49

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_13_dept_5

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_13_dept_50
Build prophet model for  store_13_dept_51
Skip  store_13_dept_51 due to lack of data
Build prophet model for  store_13_dept_52
Build prophet model for  store_13_dept_54
Build prophet model for  store_13_dept_55
Build prophet model for  store_13_dept_56

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_13_dept_58
Build prophet model for  store_13_dept_59
Build prophet model for  store_13_dept_6
Build prophet model for  store_13_dept_60
Build prophet model for  store_13_dept_67

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_13_dept_7

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_13_dept_71

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_13_dept_72

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_13_dept_74

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_13_dept_79

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_13_dept_8

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_13_dept_80

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_13_dept_81
Build prophet model for  store_13_dept_82
Build prophet model for  store_13_dept_83

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.
ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_13_dept_85
Build prophet model for  store_13_dept_87
Build prophet model for  store_13_dept_9
Build prophet model for  store_13_dept_90

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_13_dept_91

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_13_dept_92
Build prophet model for  store_13_dept_93
Build prophet model for  store_13_dept_94
Build prophet model for  store_13_dept_95

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_13_dept_96

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_13_dept_97

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_13_dept_98
Build prophet model for  store_14_dept_1
Build prophet model for  store_14_dept_10

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_14_dept_11
Build prophet model for  store_14_dept_12

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.
ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_14_dept_13
Build prophet model for  store_14_dept_14
Build prophet model for  store_14_dept_16
Build prophet model for  store_14_dept_17
Build prophet model for  store_14_dept_18

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_14_dept_19
Build prophet model for  store_14_dept_2

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_14_dept_20
Build prophet model for  store_14_dept_21
Build prophet model for  store_14_dept_22
Build prophet model for  store_14_dept_23
Build prophet model for  store_14_dept_24
Build prophet model for  store_14_dept_25
Build prophet model for  store_14_dept_26
Build prophet model for  store_14_dept_27
Build prophet model for  store_14_dept_28
Build prophet model for  store_14_dept_29
Build prophet model for  store_14_dept_3

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_14_dept_30
Build prophet model for  store_14_dept_31
Build prophet model for  store_14_dept_32
Build prophet model for  store_14_dept_33
Build prophet model for  store_14_dept_34
Build prophet model for  store_14_dept_35
Build prophet model for  store_14_dept_36

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_14_dept_38
Build prophet model for  store_14_dept_4
Build prophet model for  store_14_dept_40
Build prophet model for  store_14_dept_41

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_14_dept_42
Build prophet model for  store_14_dept_44
Build prophet model for  store_14_dept_45
Skip  store_14_dept_45 due to lack of data
Build prophet model for  store_14_dept_46

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_14_dept_49
Build prophet model for  store_14_dept_5
Build prophet model for  store_14_dept_50

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_14_dept_51
Build prophet model for  store_14_dept_52
Build prophet model for  store_14_dept_54
Build prophet model for  store_14_dept_55
Build prophet model for  store_14_dept_56
Build prophet model for  store_14_dept_58
Build prophet model for  store_14_dept_59
Build prophet model for  store_14_dept_6
Build prophet model for  store_14_dept_60
Build prophet model for  store_14_dept_67
Build prophet model for  store_14_dept_7

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_14_dept_71
Build prophet model for  store_14_dept_72

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_14_dept_74

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_14_dept_79

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_14_dept_8

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_14_dept_80

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_14_dept_81
Build prophet model for  store_14_dept_82
Build prophet model for  store_14_dept_83
Build prophet model for  store_14_dept_85
Build prophet model for  store_14_dept_87

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_14_dept_9
Build prophet model for  store_14_dept_90
Build prophet model for  store_14_dept_91
Build prophet model for  store_14_dept_92

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_14_dept_93

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_14_dept_94

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_14_dept_95
Build prophet model for  store_14_dept_97
Build prophet model for  store_14_dept_98
Build prophet model for  store_15_dept_1
Build prophet model for  store_15_dept_10
Build prophet model for  store_15_dept_11
Build prophet model for  store_15_dept_12
Build prophet model for  store_15_dept_13
Build prophet model for  store_15_dept_14
Build prophet model for  store_15_dept_16
Build prophet model for  store_15_dept_17
Build prophet model for  store_15_dept_18
Build prophet model for  store_15_dept_19
Build prophet model for  store_15_dept_2
Build prophet model for  store_15_dept_20
Build prophet model for  store_15_dept_21
Build prophet model for  store_15_dept_22
Build prophet model for  store_15_dept_23
Build prophet model for  store_15_dept_24
Build prophet model for  store_15_dept_25
Build prophet model for  store_15_dept_26
Build prophet model for  store_15_dept_27
Build prophet model for  store_15_dept_28
Build prophet model for  store_15_dept_29
Build prophet model for  store_15_dept_3
Build prophet model for  store_15_dept_30
Build prophet model for  store_15_dept_31
Build prophet model for  store_15_dept_32
Build prophet model for  store_15_dept_33
Build prophet model for  store_15_dept_34
Build prophet model for  store_15_dept_35
Build prophet model for  store_15_dept_36
Build prophet model for  store_15_dept_38
Build prophet model for  store_15_dept_4
Build prophet model for  store_15_dept_40
Build prophet model for  store_15_dept_41
Build prophet model for  store_15_dept_42
Build prophet model for  store_15_dept_44
Build prophet model for  store_15_dept_46
Build prophet model for  store_15_dept_49
Build prophet model for  store_15_dept_5
Build prophet model for  store_15_dept_50
Build prophet model for  store_15_dept_52
Build prophet model for  store_15_dept_54
Build prophet model for  store_15_dept_55
Build prophet model for  store_15_dept_56
Build prophet model for  store_15_dept_58
Build prophet model for  store_15_dept_59
Build prophet model for  store_15_dept_6
Build prophet model for  store_15_dept_67
Build prophet model for  store_15_dept_7
Build prophet model for  store_15_dept_71
Build prophet model for  store_15_dept_72
Build prophet model for  store_15_dept_74
Build prophet model for  store_15_dept_79
Build prophet model for  store_15_dept_8
Build prophet model for  store_15_dept_80
Build prophet model for  store_15_dept_81
Build prophet model for  store_15_dept_82
Build prophet model for  store_15_dept_83
Build prophet model for  store_15_dept_85
Build prophet model for  store_15_dept_87
Build prophet model for  store_15_dept_9
Build prophet model for  store_15_dept_90
Build prophet model for  store_15_dept_91
Build prophet model for  store_15_dept_92
Build prophet model for  store_15_dept_93
Build prophet model for  store_15_dept_95
Build prophet model for  store_15_dept_96
Build prophet model for  store_15_dept_97
Build prophet model for  store_16_dept_1
Build prophet model for  store_16_dept_10
Build prophet model for  store_16_dept_11
Build prophet model for  store_16_dept_12
Build prophet model for  store_16_dept_13
Build prophet model for  store_16_dept_14
Build prophet model for  store_16_dept_16
Build prophet model for  store_16_dept_17
Build prophet model for  store_16_dept_18
Build prophet model for  store_16_dept_19
Build prophet model for  store_16_dept_2
Build prophet model for  store_16_dept_20
Build prophet model for  store_16_dept_21
Build prophet model for  store_16_dept_22
Build prophet model for  store_16_dept_23
Build prophet model for  store_16_dept_24
Build prophet model for  store_16_dept_25
Build prophet model for  store_16_dept_26
Build prophet model for  store_16_dept_27
Build prophet model for  store_16_dept_28
Build prophet model for  store_16_dept_29
Build prophet model for  store_16_dept_3
Build prophet model for  store_16_dept_30
Build prophet model for  store_16_dept_31
Build prophet model for  store_16_dept_32
Build prophet model for  store_16_dept_33
Build prophet model for  store_16_dept_34
Build prophet model for  store_16_dept_35
Build prophet model for  store_16_dept_36
Build prophet model for  store_16_dept_38
Build prophet model for  store_16_dept_4
Build prophet model for  store_16_dept_40
Build prophet model for  store_16_dept_41
Build prophet model for  store_16_dept_42
Build prophet model for  store_16_dept_44
Build prophet model for  store_16_dept_46
Build prophet model for  store_16_dept_5
Build prophet model for  store_16_dept_52
Build prophet model for  store_16_dept_54
Build prophet model for  store_16_dept_55
Build prophet model for  store_16_dept_56
Build prophet model for  store_16_dept_59
Build prophet model for  store_16_dept_6
Build prophet model for  store_16_dept_67
Build prophet model for  store_16_dept_7
Build prophet model for  store_16_dept_71
Build prophet model for  store_16_dept_72
Build prophet model for  store_16_dept_74
Build prophet model for  store_16_dept_79
Build prophet model for  store_16_dept_8
Build prophet model for  store_16_dept_81
Build prophet model for  store_16_dept_82
Build prophet model for  store_16_dept_85
Build prophet model for  store_16_dept_87
Build prophet model for  store_16_dept_9
Build prophet model for  store_16_dept_90
Build prophet model for  store_16_dept_91
Build prophet model for  store_16_dept_92
Build prophet model for  store_16_dept_94
Build prophet model for  store_16_dept_95
Build prophet model for  store_16_dept_96
Build prophet model for  store_16_dept_97
Build prophet model for  store_17_dept_1
Build prophet model for  store_17_dept_10
Build prophet model for  store_17_dept_11
Build prophet model for  store_17_dept_12
Build prophet model for  store_17_dept_13
Build prophet model for  store_17_dept_14
Build prophet model for  store_17_dept_16
Build prophet model for  store_17_dept_17
Build prophet model for  store_17_dept_18
Build prophet model for  store_17_dept_19
Build prophet model for  store_17_dept_2
Build prophet model for  store_17_dept_20
Build prophet model for  store_17_dept_21
Build prophet model for  store_17_dept_22
Build prophet model for  store_17_dept_23
Build prophet model for  store_17_dept_24
Build prophet model for  store_17_dept_25
Build prophet model for  store_17_dept_26
Build prophet model for  store_17_dept_27
Build prophet model for  store_17_dept_28
Build prophet model for  store_17_dept_29
Build prophet model for  store_17_dept_3
Build prophet model for  store_17_dept_30
Build prophet model for  store_17_dept_31
Build prophet model for  store_17_dept_32
Build prophet model for  store_17_dept_33
Build prophet model for  store_17_dept_34
Build prophet model for  store_17_dept_35
Build prophet model for  store_17_dept_36
Build prophet model for  store_17_dept_38
Build prophet model for  store_17_dept_4
Build prophet model for  store_17_dept_40
Build prophet model for  store_17_dept_42
Build prophet model for  store_17_dept_44
Build prophet model for  store_17_dept_46
Build prophet model for  store_17_dept_48
Build prophet model for  store_17_dept_5
Build prophet model for  store_17_dept_51
Build prophet model for  store_17_dept_52
Build prophet model for  store_17_dept_54
Build prophet model for  store_17_dept_55
Build prophet model for  store_17_dept_56
Build prophet model for  store_17_dept_58
Build prophet model for  store_17_dept_59
Build prophet model for  store_17_dept_6
Build prophet model for  store_17_dept_60
Build prophet model for  store_17_dept_67
Build prophet model for  store_17_dept_7
Build prophet model for  store_17_dept_71
Build prophet model for  store_17_dept_72
Build prophet model for  store_17_dept_74
Build prophet model for  store_17_dept_79
Build prophet model for  store_17_dept_8
Build prophet model for  store_17_dept_80
Build prophet model for  store_17_dept_81
Build prophet model for  store_17_dept_82
Build prophet model for  store_17_dept_83
Build prophet model for  store_17_dept_85
Build prophet model for  store_17_dept_87
Build prophet model for  store_17_dept_9
Build prophet model for  store_17_dept_90
Build prophet model for  store_17_dept_91
Build prophet model for  store_17_dept_92
Build prophet model for  store_17_dept_93
Build prophet model for  store_17_dept_95
Build prophet model for  store_17_dept_97
Build prophet model for  store_18_dept_1
Build prophet model for  store_18_dept_10
Build prophet model for  store_18_dept_11
Build prophet model for  store_18_dept_12
Build prophet model for  store_18_dept_13
Build prophet model for  store_18_dept_14
Build prophet model for  store_18_dept_16
Build prophet model for  store_18_dept_17
Build prophet model for  store_18_dept_18
Build prophet model for  store_18_dept_19
Build prophet model for  store_18_dept_2
Build prophet model for  store_18_dept_20
Build prophet model for  store_18_dept_21
Build prophet model for  store_18_dept_22
Build prophet model for  store_18_dept_23
Build prophet model for  store_18_dept_24
Build prophet model for  store_18_dept_25
Build prophet model for  store_18_dept_26
Build prophet model for  store_18_dept_27
Build prophet model for  store_18_dept_28
Build prophet model for  store_18_dept_29
Build prophet model for  store_18_dept_3
Build prophet model for  store_18_dept_30
Build prophet model for  store_18_dept_31
Build prophet model for  store_18_dept_32
Build prophet model for  store_18_dept_33
Build prophet model for  store_18_dept_34
Build prophet model for  store_18_dept_35
Build prophet model for  store_18_dept_36
Build prophet model for  store_18_dept_38
Build prophet model for  store_18_dept_4
Build prophet model for  store_18_dept_40
Build prophet model for  store_18_dept_41
Build prophet model for  store_18_dept_42
Build prophet model for  store_18_dept_44
Build prophet model for  store_18_dept_46
Build prophet model for  store_18_dept_49
Build prophet model for  store_18_dept_5
Build prophet model for  store_18_dept_52
Build prophet model for  store_18_dept_54
Build prophet model for  store_18_dept_55
Build prophet model for  store_18_dept_56
Build prophet model for  store_18_dept_58
Build prophet model for  store_18_dept_59
Build prophet model for  store_18_dept_6
Build prophet model for  store_18_dept_67
Build prophet model for  store_18_dept_7
Build prophet model for  store_18_dept_71
Build prophet model for  store_18_dept_72
Build prophet model for  store_18_dept_74
Build prophet model for  store_18_dept_79
Build prophet model for  store_18_dept_8
Build prophet model for  store_18_dept_81
Build prophet model for  store_18_dept_82
Build prophet model for  store_18_dept_83
Build prophet model for  store_18_dept_85
Build prophet model for  store_18_dept_87
Build prophet model for  store_18_dept_9
Build prophet model for  store_18_dept_90
Build prophet model for  store_18_dept_91
Build prophet model for  store_18_dept_92
Build prophet model for  store_18_dept_93
Build prophet model for  store_18_dept_95
Build prophet model for  store_18_dept_97
Build prophet model for  store_19_dept_1
Build prophet model for  store_19_dept_10
Build prophet model for  store_19_dept_11
Build prophet model for  store_19_dept_12

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.
ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_19_dept_13
Build prophet model for  store_19_dept_14
Build prophet model for  store_19_dept_16
Build prophet model for  store_19_dept_17
Build prophet model for  store_19_dept_18

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_19_dept_2
Build prophet model for  store_19_dept_20
Build prophet model for  store_19_dept_21
Build prophet model for  store_19_dept_22
Build prophet model for  store_19_dept_23
Build prophet model for  store_19_dept_24
Build prophet model for  store_19_dept_25
Build prophet model for  store_19_dept_26
Build prophet model for  store_19_dept_27
Build prophet model for  store_19_dept_28
Build prophet model for  store_19_dept_29

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_19_dept_3
Build prophet model for  store_19_dept_30
Build prophet model for  store_19_dept_31
Build prophet model for  store_19_dept_32
Build prophet model for  store_19_dept_33
Build prophet model for  store_19_dept_34
Build prophet model for  store_19_dept_35
Build prophet model for  store_19_dept_36

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_19_dept_37
Build prophet model for  store_19_dept_38

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_19_dept_4

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_19_dept_40
Build prophet model for  store_19_dept_41

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_19_dept_42
Build prophet model for  store_19_dept_44
Build prophet model for  store_19_dept_46
Build prophet model for  store_19_dept_49
Build prophet model for  store_19_dept_5
Build prophet model for  store_19_dept_50
Build prophet model for  store_19_dept_52
Build prophet model for  store_19_dept_54
Build prophet model for  store_19_dept_55
Build prophet model for  store_19_dept_56
Build prophet model for  store_19_dept_58
Build prophet model for  store_19_dept_59
Build prophet model for  store_19_dept_6
Build prophet model for  store_19_dept_60
Build prophet model for  store_19_dept_67
Build prophet model for  store_19_dept_7
Build prophet model for  store_19_dept_71

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_19_dept_72

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_19_dept_74
Build prophet model for  store_19_dept_79

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_19_dept_8

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_19_dept_80

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_19_dept_81
Build prophet model for  store_19_dept_82
Build prophet model for  store_19_dept_83

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_19_dept_85
Build prophet model for  store_19_dept_87

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_19_dept_9
Build prophet model for  store_19_dept_90

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_19_dept_91

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_19_dept_92
Build prophet model for  store_19_dept_93

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_19_dept_94
Build prophet model for  store_19_dept_95
Build prophet model for  store_19_dept_96

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_19_dept_97
Build prophet model for  store_19_dept_98
Build prophet model for  store_1_dept_1
Build prophet model for  store_1_dept_10
Build prophet model for  store_1_dept_11
Build prophet model for  store_1_dept_12
Build prophet model for  store_1_dept_13

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_1_dept_14
Build prophet model for  store_1_dept_16
Build prophet model for  store_1_dept_17
Build prophet model for  store_1_dept_18
Build prophet model for  store_1_dept_19
Build prophet model for  store_1_dept_2
Build prophet model for  store_1_dept_20
Build prophet model for  store_1_dept_21
Build prophet model for  store_1_dept_22
Build prophet model for  store_1_dept_23
Build prophet model for  store_1_dept_24
Build prophet model for  store_1_dept_25
Build prophet model for  store_1_dept_26
Build prophet model for  store_1_dept_27
Build prophet model for  store_1_dept_28
Build prophet model for  store_1_dept_29
Build prophet model for  store_1_dept_3
Build prophet model for  store_1_dept_30
Build prophet model for  store_1_dept_31
Build prophet model for  store_1_dept_32
Build prophet model for  store_1_dept_33
Build prophet model for  store_1_dept_34
Build prophet model for  store_1_dept_35
Build prophet model for  store_1_dept_36

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_1_dept_37
Build prophet model for  store_1_dept_38
Build prophet model for  store_1_dept_4

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_1_dept_40
Build prophet model for  store_1_dept_41
Build prophet model for  store_1_dept_42

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_1_dept_44
Build prophet model for  store_1_dept_45
Build prophet model for  store_1_dept_46
Build prophet model for  store_1_dept_48
Build prophet model for  store_1_dept_49
Build prophet model for  store_1_dept_5
Build prophet model for  store_1_dept_51
Skip  store_1_dept_51 due to lack of data
Build prophet model for  store_1_dept_52
Build prophet model for  store_1_dept_54
Build prophet model for  store_1_dept_55
Build prophet model for  store_1_dept_56
Build prophet model for  store_1_dept_58
Build prophet model for  store_1_dept_59
Build prophet model for  store_1_dept_6
Build prophet model for  store_1_dept_60
Build prophet model for  store_1_dept_67
Build prophet model for  store_1_dept_7
Build prophet model for  store_1_dept_71
Build prophet model for  store_1_dept_72

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_1_dept_74
Build prophet model for  store_1_dept_79

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_1_dept_8
Build prophet model for  store_1_dept_80
Build prophet model for  store_1_dept_81

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_1_dept_82
Build prophet model for  store_1_dept_83
Build prophet model for  store_1_dept_85
Build prophet model for  store_1_dept_87
Build prophet model for  store_1_dept_9
Build prophet model for  store_1_dept_90

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_1_dept_91
Build prophet model for  store_1_dept_92
Build prophet model for  store_1_dept_93
Build prophet model for  store_1_dept_94
Build prophet model for  store_1_dept_95
Build prophet model for  store_1_dept_97
Build prophet model for  store_1_dept_98

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_20_dept_1
Build prophet model for  store_20_dept_10

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_20_dept_11
Build prophet model for  store_20_dept_12

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_20_dept_13
Build prophet model for  store_20_dept_14
Build prophet model for  store_20_dept_16
Build prophet model for  store_20_dept_17
Build prophet model for  store_20_dept_18
Build prophet model for  store_20_dept_2

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_20_dept_20
Build prophet model for  store_20_dept_21
Build prophet model for  store_20_dept_22
Build prophet model for  store_20_dept_23
Build prophet model for  store_20_dept_24
Build prophet model for  store_20_dept_25
Build prophet model for  store_20_dept_26
Build prophet model for  store_20_dept_27
Build prophet model for  store_20_dept_28
Build prophet model for  store_20_dept_29
Build prophet model for  store_20_dept_3

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_20_dept_30
Build prophet model for  store_20_dept_31
Build prophet model for  store_20_dept_32
Build prophet model for  store_20_dept_33
Build prophet model for  store_20_dept_34

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_20_dept_35
Build prophet model for  store_20_dept_36

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_20_dept_37

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_20_dept_38
Build prophet model for  store_20_dept_4
Build prophet model for  store_20_dept_40
Build prophet model for  store_20_dept_41

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_20_dept_42
Build prophet model for  store_20_dept_44
Build prophet model for  store_20_dept_46

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_20_dept_49
Build prophet model for  store_20_dept_5
Build prophet model for  store_20_dept_50

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_20_dept_52
Build prophet model for  store_20_dept_54
Build prophet model for  store_20_dept_55
Build prophet model for  store_20_dept_56
Build prophet model for  store_20_dept_58
Build prophet model for  store_20_dept_59
Build prophet model for  store_20_dept_6
Build prophet model for  store_20_dept_60
Build prophet model for  store_20_dept_67
Build prophet model for  store_20_dept_7
Build prophet model for  store_20_dept_71
Build prophet model for  store_20_dept_72
Build prophet model for  store_20_dept_74
Build prophet model for  store_20_dept_79

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_20_dept_8
Build prophet model for  store_20_dept_80

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.
ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_20_dept_81
Build prophet model for  store_20_dept_82
Build prophet model for  store_20_dept_83

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_20_dept_85
Build prophet model for  store_20_dept_87
Build prophet model for  store_20_dept_9
Build prophet model for  store_20_dept_90

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_20_dept_91

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_20_dept_92
Build prophet model for  store_20_dept_93

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_20_dept_94

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_20_dept_95
Build prophet model for  store_20_dept_97

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_20_dept_98
Build prophet model for  store_21_dept_1
Build prophet model for  store_21_dept_10
Build prophet model for  store_21_dept_11
Build prophet model for  store_21_dept_12
Build prophet model for  store_21_dept_13
Build prophet model for  store_21_dept_14
Build prophet model for  store_21_dept_16
Build prophet model for  store_21_dept_17
Build prophet model for  store_21_dept_18
Build prophet model for  store_21_dept_19
Build prophet model for  store_21_dept_2
Build prophet model for  store_21_dept_20
Build prophet model for  store_21_dept_21
Build prophet model for  store_21_dept_22
Build prophet model for  store_21_dept_23
Build prophet model for  store_21_dept_24
Build prophet model for  store_21_dept_25
Build prophet model for  store_21_dept_26
Build prophet model for  store_21_dept_27
Build prophet model for  store_21_dept_28
Build prophet model for  store_21_dept_29
Build prophet model for  store_21_dept_3
Build prophet model for  store_21_dept_30
Build prophet model for  store_21_dept_31
Build prophet model for  store_21_dept_32
Build prophet model for  store_21_dept_33
Build prophet model for  store_21_dept_34
Build prophet model for  store_21_dept_35
Build prophet model for  store_21_dept_36
Build prophet model for  store_21_dept_38
Build prophet model for  store_21_dept_4
Build prophet model for  store_21_dept_40

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_21_dept_41
Build prophet model for  store_21_dept_42
Build prophet model for  store_21_dept_44
Build prophet model for  store_21_dept_46
Build prophet model for  store_21_dept_49
Build prophet model for  store_21_dept_5
Build prophet model for  store_21_dept_52
Build prophet model for  store_21_dept_54
Build prophet model for  store_21_dept_55
Build prophet model for  store_21_dept_56
Build prophet model for  store_21_dept_58
Build prophet model for  store_21_dept_59
Build prophet model for  store_21_dept_6
Build prophet model for  store_21_dept_67
Build prophet model for  store_21_dept_7
Build prophet model for  store_21_dept_71
Build prophet model for  store_21_dept_72
Build prophet model for  store_21_dept_74
Build prophet model for  store_21_dept_79
Build prophet model for  store_21_dept_8
Build prophet model for  store_21_dept_81
Build prophet model for  store_21_dept_82
Build prophet model for  store_21_dept_83
Build prophet model for  store_21_dept_85
Build prophet model for  store_21_dept_87
Build prophet model for  store_21_dept_9
Build prophet model for  store_21_dept_90
Build prophet model for  store_21_dept_91
Build prophet model for  store_21_dept_92
Build prophet model for  store_21_dept_93
Build prophet model for  store_21_dept_95
Build prophet model for  store_21_dept_97
Build prophet model for  store_22_dept_1
Build prophet model for  store_22_dept_10
Build prophet model for  store_22_dept_11
Build prophet model for  store_22_dept_12
Build prophet model for  store_22_dept_13
Build prophet model for  store_22_dept_14
Build prophet model for  store_22_dept_16
Build prophet model for  store_22_dept_17
Build prophet model for  store_22_dept_18
Build prophet model for  store_22_dept_2
Build prophet model for  store_22_dept_20
Build prophet model for  store_22_dept_21
Build prophet model for  store_22_dept_22
Build prophet model for  store_22_dept_23
Build prophet model for  store_22_dept_24
Build prophet model for  store_22_dept_25
Build prophet model for  store_22_dept_26
Build prophet model for  store_22_dept_27
Build prophet model for  store_22_dept_28
Build prophet model for  store_22_dept_29
Build prophet model for  store_22_dept_3
Build prophet model for  store_22_dept_30
Build prophet model for  store_22_dept_31
Build prophet model for  store_22_dept_32
Build prophet model for  store_22_dept_33
Build prophet model for  store_22_dept_34
Build prophet model for  store_22_dept_35
Build prophet model for  store_22_dept_36
Build prophet model for  store_22_dept_38
Build prophet model for  store_22_dept_4
Build prophet model for  store_22_dept_40
Build prophet model for  store_22_dept_41
Build prophet model for  store_22_dept_42
Build prophet model for  store_22_dept_44
Build prophet model for  store_22_dept_46
Build prophet model for  store_22_dept_5
Build prophet model for  store_22_dept_51
Skip  store_22_dept_51 due to lack of data
Build prophet model for  store_22_dept_52
Build prophet model for  store_22_dept_54
Build prophet model for  store_22_dept_55
Build prophet model for  store_22_dept_56
Build prophet model for  store_22_dept_58
Build prophet model for  store_22_dept_59
Build prophet model for  store_22_dept_6
Build prophet model for  store_22_dept_60
Build prophet model for  store_22_dept_67
Build prophet model for  store_22_dept_7
Build prophet model for  store_22_dept_71
Build prophet model for  store_22_dept_72
Build prophet model for  store_22_dept_74
Build prophet model for  store_22_dept_79
Build prophet model for  store_22_dept_8
Build prophet model for  store_22_dept_80
Build prophet model for  store_22_dept_81
Build prophet model for  store_22_dept_82
Build prophet model for  store_22_dept_83
Build prophet model for  store_22_dept_85
Build prophet model for  store_22_dept_87
Build prophet model for  store_22_dept_9
Build prophet model for  store_22_dept_90
Build prophet model for  store_22_dept_91
Build prophet model for  store_22_dept_92
Build prophet model for  store_22_dept_93
Build prophet model for  store_22_dept_95
Build prophet model for  store_22_dept_97
Build prophet model for  store_23_dept_1
Build prophet model for  store_23_dept_10
Build prophet model for  store_23_dept_11
Build prophet model for  store_23_dept_12
Build prophet model for  store_23_dept_13
Build prophet model for  store_23_dept_14
Build prophet model for  store_23_dept_16
Build prophet model for  store_23_dept_17
Build prophet model for  store_23_dept_18
Build prophet model for  store_23_dept_19
Build prophet model for  store_23_dept_2
Build prophet model for  store_23_dept_20
Build prophet model for  store_23_dept_21
Build prophet model for  store_23_dept_22
Build prophet model for  store_23_dept_23
Build prophet model for  store_23_dept_24
Build prophet model for  store_23_dept_25
Build prophet model for  store_23_dept_26
Build prophet model for  store_23_dept_27
Build prophet model for  store_23_dept_28
Build prophet model for  store_23_dept_29
Build prophet model for  store_23_dept_3
Build prophet model for  store_23_dept_30
Build prophet model for  store_23_dept_31
Build prophet model for  store_23_dept_32
Build prophet model for  store_23_dept_33
Build prophet model for  store_23_dept_34
Build prophet model for  store_23_dept_35
Build prophet model for  store_23_dept_36
Build prophet model for  store_23_dept_38
Build prophet model for  store_23_dept_4
Build prophet model for  store_23_dept_40
Build prophet model for  store_23_dept_41
Build prophet model for  store_23_dept_42
Build prophet model for  store_23_dept_44
Build prophet model for  store_23_dept_45
Build prophet model for  store_23_dept_46
Build prophet model for  store_23_dept_49
Build prophet model for  store_23_dept_5
Build prophet model for  store_23_dept_50
Build prophet model for  store_23_dept_51
Skip  store_23_dept_51 due to lack of data
Build prophet model for  store_23_dept_52
Build prophet model for  store_23_dept_54
Build prophet model for  store_23_dept_55
Build prophet model for  store_23_dept_56
Build prophet model for  store_23_dept_58
Build prophet model for  store_23_dept_59
Build prophet model for  store_23_dept_6
Build prophet model for  store_23_dept_67
Build prophet model for  store_23_dept_7
Build prophet model for  store_23_dept_71
Build prophet model for  store_23_dept_72
Build prophet model for  store_23_dept_74
Build prophet model for  store_23_dept_79
Build prophet model for  store_23_dept_8
Build prophet model for  store_23_dept_81
Build prophet model for  store_23_dept_82
Build prophet model for  store_23_dept_83
Build prophet model for  store_23_dept_85
Build prophet model for  store_23_dept_87
Build prophet model for  store_23_dept_9
Build prophet model for  store_23_dept_90
Build prophet model for  store_23_dept_91
Build prophet model for  store_23_dept_92
Build prophet model for  store_23_dept_93
Build prophet model for  store_23_dept_94
Build prophet model for  store_23_dept_95
Build prophet model for  store_23_dept_96
Build prophet model for  store_23_dept_97
Build prophet model for  store_24_dept_1
Build prophet model for  store_24_dept_10
Build prophet model for  store_24_dept_11

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_24_dept_12

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_24_dept_13
Build prophet model for  store_24_dept_14
Build prophet model for  store_24_dept_16
Build prophet model for  store_24_dept_17
Build prophet model for  store_24_dept_18

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_24_dept_19
Build prophet model for  store_24_dept_2

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_24_dept_20
Build prophet model for  store_24_dept_21
Build prophet model for  store_24_dept_22
Build prophet model for  store_24_dept_23
Build prophet model for  store_24_dept_24
Build prophet model for  store_24_dept_25
Build prophet model for  store_24_dept_26
Build prophet model for  store_24_dept_27
Build prophet model for  store_24_dept_28
Build prophet model for  store_24_dept_29
Build prophet model for  store_24_dept_3
Build prophet model for  store_24_dept_30

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_24_dept_31
Build prophet model for  store_24_dept_32
Build prophet model for  store_24_dept_33
Build prophet model for  store_24_dept_34
Build prophet model for  store_24_dept_35
Build prophet model for  store_24_dept_36

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_24_dept_37

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_24_dept_38

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_24_dept_4

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_24_dept_40

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_24_dept_41
Build prophet model for  store_24_dept_42
Build prophet model for  store_24_dept_44
Build prophet model for  store_24_dept_46

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_24_dept_49

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_24_dept_5
Build prophet model for  store_24_dept_50
Build prophet model for  store_24_dept_52
Build prophet model for  store_24_dept_54
Build prophet model for  store_24_dept_55
Build prophet model for  store_24_dept_56
Build prophet model for  store_24_dept_58
Build prophet model for  store_24_dept_59
Build prophet model for  store_24_dept_6
Build prophet model for  store_24_dept_67
Build prophet model for  store_24_dept_7
Build prophet model for  store_24_dept_71
Build prophet model for  store_24_dept_72
Build prophet model for  store_24_dept_74

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.
ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_24_dept_79

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_24_dept_8

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_24_dept_80

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_24_dept_81
Build prophet model for  store_24_dept_82
Build prophet model for  store_24_dept_83
Build prophet model for  store_24_dept_85
Build prophet model for  store_24_dept_87

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.
ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_24_dept_9
Build prophet model for  store_24_dept_90

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_24_dept_91

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_24_dept_92
Build prophet model for  store_24_dept_93

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_24_dept_94
Build prophet model for  store_24_dept_95
Build prophet model for  store_24_dept_96

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_24_dept_97

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_24_dept_98
Build prophet model for  store_25_dept_1
Build prophet model for  store_25_dept_10
Build prophet model for  store_25_dept_11
Build prophet model for  store_25_dept_12
Build prophet model for  store_25_dept_13
Build prophet model for  store_25_dept_14
Build prophet model for  store_25_dept_16
Build prophet model for  store_25_dept_17
Build prophet model for  store_25_dept_18
Build prophet model for  store_25_dept_2
Build prophet model for  store_25_dept_20
Build prophet model for  store_25_dept_21
Build prophet model for  store_25_dept_22
Build prophet model for  store_25_dept_23
Build prophet model for  store_25_dept_24
Build prophet model for  store_25_dept_25
Build prophet model for  store_25_dept_26
Build prophet model for  store_25_dept_27
Build prophet model for  store_25_dept_28
Build prophet model for  store_25_dept_29
Build prophet model for  store_25_dept_3
Build prophet model for  store_25_dept_30
Build prophet model for  store_25_dept_31
Build prophet model for  store_25_dept_32
Build prophet model for  store_25_dept_33
Build prophet model for  store_25_dept_34
Build prophet model for  store_25_dept_35
Build prophet model for  store_25_dept_36
Build prophet model for  store_25_dept_37
Build prophet model for  store_25_dept_38
Build prophet model for  store_25_dept_4
Build prophet model for  store_25_dept_40

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_25_dept_41
Build prophet model for  store_25_dept_42
Build prophet model for  store_25_dept_44
Build prophet model for  store_25_dept_46
Build prophet model for  store_25_dept_49
Build prophet model for  store_25_dept_5
Build prophet model for  store_25_dept_50
Build prophet model for  store_25_dept_52
Build prophet model for  store_25_dept_54
Build prophet model for  store_25_dept_55
Build prophet model for  store_25_dept_56
Build prophet model for  store_25_dept_59
Build prophet model for  store_25_dept_6
Build prophet model for  store_25_dept_67
Build prophet model for  store_25_dept_7
Build prophet model for  store_25_dept_71
Build prophet model for  store_25_dept_72
Build prophet model for  store_25_dept_74
Build prophet model for  store_25_dept_79
Build prophet model for  store_25_dept_8
Build prophet model for  store_25_dept_81
Build prophet model for  store_25_dept_82
Build prophet model for  store_25_dept_83
Build prophet model for  store_25_dept_85
Build prophet model for  store_25_dept_87
Build prophet model for  store_25_dept_9
Build prophet model for  store_25_dept_90
Build prophet model for  store_25_dept_91
Build prophet model for  store_25_dept_92
Build prophet model for  store_25_dept_93
Build prophet model for  store_25_dept_95
Build prophet model for  store_25_dept_97
Build prophet model for  store_25_dept_98
Build prophet model for  store_26_dept_1
Build prophet model for  store_26_dept_10
Build prophet model for  store_26_dept_11
Build prophet model for  store_26_dept_12

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_26_dept_13
Build prophet model for  store_26_dept_14
Build prophet model for  store_26_dept_16
Build prophet model for  store_26_dept_17
Build prophet model for  store_26_dept_18
Build prophet model for  store_26_dept_19
Build prophet model for  store_26_dept_2
Build prophet model for  store_26_dept_20
Build prophet model for  store_26_dept_21
Build prophet model for  store_26_dept_22
Build prophet model for  store_26_dept_23
Build prophet model for  store_26_dept_24
Build prophet model for  store_26_dept_25
Build prophet model for  store_26_dept_26
Build prophet model for  store_26_dept_27
Build prophet model for  store_26_dept_28
Build prophet model for  store_26_dept_29
Build prophet model for  store_26_dept_3
Build prophet model for  store_26_dept_30
Build prophet model for  store_26_dept_31
Build prophet model for  store_26_dept_32
Build prophet model for  store_26_dept_33
Build prophet model for  store_26_dept_34
Build prophet model for  store_26_dept_35
Build prophet model for  store_26_dept_36

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_26_dept_38
Build prophet model for  store_26_dept_4

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_26_dept_40
Build prophet model for  store_26_dept_41
Build prophet model for  store_26_dept_42
Build prophet model for  store_26_dept_44
Build prophet model for  store_26_dept_46
Build prophet model for  store_26_dept_49
Build prophet model for  store_26_dept_5
Build prophet model for  store_26_dept_52
Build prophet model for  store_26_dept_54
Build prophet model for  store_26_dept_55
Build prophet model for  store_26_dept_56
Build prophet model for  store_26_dept_59
Build prophet model for  store_26_dept_6
Build prophet model for  store_26_dept_67
Build prophet model for  store_26_dept_7
Build prophet model for  store_26_dept_71
Build prophet model for  store_26_dept_72
Build prophet model for  store_26_dept_74
Build prophet model for  store_26_dept_79
Build prophet model for  store_26_dept_8
Build prophet model for  store_26_dept_80
Build prophet model for  store_26_dept_81
Build prophet model for  store_26_dept_82
Build prophet model for  store_26_dept_83
Build prophet model for  store_26_dept_85
Build prophet model for  store_26_dept_87
Build prophet model for  store_26_dept_9
Build prophet model for  store_26_dept_90
Build prophet model for  store_26_dept_91
Build prophet model for  store_26_dept_92
Build prophet model for  store_26_dept_93

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted

Build prophet model for  store_26_dept_94
Build prophet model for  store_26_dept_95

WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_26_dept_96
Build prophet model for  store_26_dept_97
Build prophet model for  store_26_dept_98
Build prophet model for  store_27_dept_1

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_27_dept_10

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted

Build prophet model for  store_27_dept_11
Build prophet model for  store_27_dept_12

WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.
ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_27_dept_13
Build prophet model for  store_27_dept_14
Build prophet model for  store_27_dept_16
Build prophet model for  store_27_dept_17
Build prophet model for  store_27_dept_18
Build prophet model for  store_27_dept_19

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_27_dept_2
Build prophet model for  store_27_dept_20
Build prophet model for  store_27_dept_21
Build prophet model for  store_27_dept_22
Build prophet model for  store_27_dept_23
Build prophet model for  store_27_dept_24
Build prophet model for  store_27_dept_25
Build prophet model for  store_27_dept_26
Build prophet model for  store_27_dept_27
Build prophet model for  store_27_dept_28
Build prophet model for  store_27_dept_29

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_27_dept_3
Build prophet model for  store_27_dept_30
Build prophet model for  store_27_dept_31
Build prophet model for  store_27_dept_32

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_27_dept_33
Build prophet model for  store_27_dept_34
Build prophet model for  store_27_dept_35
Build prophet model for  store_27_dept_36

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_27_dept_37

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_27_dept_38

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_27_dept_4

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_27_dept_40

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_27_dept_41
Build prophet model for  store_27_dept_42
Build prophet model for  store_27_dept_44
Build prophet model for  store_27_dept_46

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_27_dept_49

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_27_dept_5
Build prophet model for  store_27_dept_50
Build prophet model for  store_27_dept_52
Build prophet model for  store_27_dept_54
Build prophet model for  store_27_dept_55
Build prophet model for  store_27_dept_56
Build prophet model for  store_27_dept_58
Build prophet model for  store_27_dept_59
Build prophet model for  store_27_dept_6
Build prophet model for  store_27_dept_67
Build prophet model for  store_27_dept_7
Build prophet model for  store_27_dept_71
Build prophet model for  store_27_dept_72

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.
ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_27_dept_74

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_27_dept_79

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_27_dept_8

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_27_dept_80

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_27_dept_81
Build prophet model for  store_27_dept_82
Build prophet model for  store_27_dept_83

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_27_dept_85
Build prophet model for  store_27_dept_87
Build prophet model for  store_27_dept_9
Build prophet model for  store_27_dept_90

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_27_dept_91

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_27_dept_92
Build prophet model for  store_27_dept_93

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_27_dept_94
Build prophet model for  store_27_dept_95
Build prophet model for  store_27_dept_96

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_27_dept_97
Build prophet model for  store_27_dept_98
Build prophet model for  store_28_dept_1

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_28_dept_10
Build prophet model for  store_28_dept_11

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_28_dept_12

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_28_dept_13
Build prophet model for  store_28_dept_14
Build prophet model for  store_28_dept_16

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_28_dept_17
Build prophet model for  store_28_dept_18

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_28_dept_19
Build prophet model for  store_28_dept_2

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_28_dept_20

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_28_dept_21
Build prophet model for  store_28_dept_22
Build prophet model for  store_28_dept_23

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_28_dept_24
Build prophet model for  store_28_dept_25
Build prophet model for  store_28_dept_26
Build prophet model for  store_28_dept_27
Build prophet model for  store_28_dept_28
Build prophet model for  store_28_dept_29
Build prophet model for  store_28_dept_3

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_28_dept_30
Build prophet model for  store_28_dept_31
Build prophet model for  store_28_dept_32
Build prophet model for  store_28_dept_33

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_28_dept_34
Build prophet model for  store_28_dept_35
Build prophet model for  store_28_dept_36

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_28_dept_37

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_28_dept_38

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_28_dept_4

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_28_dept_40

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_28_dept_41
Build prophet model for  store_28_dept_42
Build prophet model for  store_28_dept_44
Build prophet model for  store_28_dept_46

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_28_dept_49

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_28_dept_5
Build prophet model for  store_28_dept_52
Build prophet model for  store_28_dept_54
Build prophet model for  store_28_dept_55
Build prophet model for  store_28_dept_56
Build prophet model for  store_28_dept_58
Build prophet model for  store_28_dept_59
Build prophet model for  store_28_dept_6
Build prophet model for  store_28_dept_60
Build prophet model for  store_28_dept_67

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_28_dept_7
Build prophet model for  store_28_dept_71
Build prophet model for  store_28_dept_72
Build prophet model for  store_28_dept_74

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.
ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_28_dept_79

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_28_dept_8

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_28_dept_80

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_28_dept_81
Build prophet model for  store_28_dept_82
Build prophet model for  store_28_dept_83
Build prophet model for  store_28_dept_85

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_28_dept_87

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_28_dept_9

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_28_dept_90

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_28_dept_91

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_28_dept_92

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_28_dept_93

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_28_dept_94
Build prophet model for  store_28_dept_95
Build prophet model for  store_28_dept_96

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_28_dept_97
Build prophet model for  store_28_dept_98
Build prophet model for  store_29_dept_1
Build prophet model for  store_29_dept_10
Build prophet model for  store_29_dept_11
Build prophet model for  store_29_dept_12
Build prophet model for  store_29_dept_13
Build prophet model for  store_29_dept_14
Build prophet model for  store_29_dept_16
Build prophet model for  store_29_dept_17
Build prophet model for  store_29_dept_18
Build prophet model for  store_29_dept_2
Build prophet model for  store_29_dept_20
Build prophet model for  store_29_dept_21
Build prophet model for  store_29_dept_22
Build prophet model for  store_29_dept_23
Build prophet model for  store_29_dept_24
Build prophet model for  store_29_dept_25
Build prophet model for  store_29_dept_26
Build prophet model for  store_29_dept_27
Build prophet model for  store_29_dept_28
Build prophet model for  store_29_dept_29
Build prophet model for  store_29_dept_3
Build prophet model for  store_29_dept_30
Build prophet model for  store_29_dept_31
Build prophet model for  store_29_dept_32
Build prophet model for  store_29_dept_33
Build prophet model for  store_29_dept_34
Build prophet model for  store_29_dept_35
Build prophet model for  store_29_dept_36
Build prophet model for  store_29_dept_38
Build prophet model for  store_29_dept_4
Build prophet model for  store_29_dept_40
Build prophet model for  store_29_dept_41
Build prophet model for  store_29_dept_42
Build prophet model for  store_29_dept_44
Build prophet model for  store_29_dept_46
Build prophet model for  store_29_dept_5
Build prophet model for  store_29_dept_52
Build prophet model for  store_29_dept_54
Build prophet model for  store_29_dept_55
Build prophet model for  store_29_dept_56

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_29_dept_58
Build prophet model for  store_29_dept_59
Build prophet model for  store_29_dept_6
Build prophet model for  store_29_dept_67
Build prophet model for  store_29_dept_7
Build prophet model for  store_29_dept_71
Build prophet model for  store_29_dept_72
Build prophet model for  store_29_dept_74
Build prophet model for  store_29_dept_79
Build prophet model for  store_29_dept_8
Build prophet model for  store_29_dept_81
Build prophet model for  store_29_dept_82
Build prophet model for  store_29_dept_83
Build prophet model for  store_29_dept_85
Build prophet model for  store_29_dept_87
Build prophet model for  store_29_dept_9
Build prophet model for  store_29_dept_90
Build prophet model for  store_29_dept_91
Build prophet model for  store_29_dept_92
Build prophet model for  store_29_dept_93
Build prophet model for  store_29_dept_95
Build prophet model for  store_29_dept_97
Build prophet model for  store_2_dept_1

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_2_dept_10

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_2_dept_11

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_2_dept_12

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_2_dept_13
Build prophet model for  store_2_dept_14
Build prophet model for  store_2_dept_16
Build prophet model for  store_2_dept_17
Build prophet model for  store_2_dept_18

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_2_dept_19
Build prophet model for  store_2_dept_2

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_2_dept_20
Build prophet model for  store_2_dept_21
Build prophet model for  store_2_dept_22
Build prophet model for  store_2_dept_23
Build prophet model for  store_2_dept_24
Build prophet model for  store_2_dept_25
Build prophet model for  store_2_dept_26
Build prophet model for  store_2_dept_27
Build prophet model for  store_2_dept_28
Build prophet model for  store_2_dept_29
Build prophet model for  store_2_dept_3
Build prophet model for  store_2_dept_30
Build prophet model for  store_2_dept_31
Build prophet model for  store_2_dept_32
Build prophet model for  store_2_dept_33

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_2_dept_34
Build prophet model for  store_2_dept_35
Build prophet model for  store_2_dept_36

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_2_dept_37
Build prophet model for  store_2_dept_38
Build prophet model for  store_2_dept_4

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.
ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_2_dept_40

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_2_dept_41
Build prophet model for  store_2_dept_42
Build prophet model for  store_2_dept_44
Build prophet model for  store_2_dept_45
Build prophet model for  store_2_dept_46
Build prophet model for  store_2_dept_48

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_2_dept_49
Build prophet model for  store_2_dept_5
Build prophet model for  store_2_dept_52
Build prophet model for  store_2_dept_54
Build prophet model for  store_2_dept_55
Build prophet model for  store_2_dept_56
Build prophet model for  store_2_dept_58
Build prophet model for  store_2_dept_59
Build prophet model for  store_2_dept_6
Build prophet model for  store_2_dept_67
Build prophet model for  store_2_dept_7

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_2_dept_71
Build prophet model for  store_2_dept_72

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_2_dept_74

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_2_dept_79

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_2_dept_8

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_2_dept_80

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_2_dept_81

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_2_dept_82
Build prophet model for  store_2_dept_83
Build prophet model for  store_2_dept_85
Build prophet model for  store_2_dept_87
Build prophet model for  store_2_dept_9
Build prophet model for  store_2_dept_90
Build prophet model for  store_2_dept_91
Build prophet model for  store_2_dept_92

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_2_dept_93

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_2_dept_94

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_2_dept_95
Build prophet model for  store_2_dept_96

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_2_dept_97
Build prophet model for  store_2_dept_98
Build prophet model for  store_30_dept_1
Build prophet model for  store_30_dept_10
Build prophet model for  store_30_dept_11
Build prophet model for  store_30_dept_12
Build prophet model for  store_30_dept_13
Build prophet model for  store_30_dept_14
Build prophet model for  store_30_dept_16
Build prophet model for  store_30_dept_17
Build prophet model for  store_30_dept_18
Build prophet model for  store_30_dept_2
Build prophet model for  store_30_dept_21
Build prophet model for  store_30_dept_25
Build prophet model for  store_30_dept_28
Build prophet model for  store_30_dept_3
Build prophet model for  store_30_dept_38
Build prophet model for  store_30_dept_4
Build prophet model for  store_30_dept_40

INFO:prophet:n_changepoints greater than number of observations. Using 6.

Build prophet model for  store_30_dept_42
Build prophet model for  store_30_dept_44
Build prophet model for  store_30_dept_46
Build prophet model for  store_30_dept_5

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_30_dept_52
Build prophet model for  store_30_dept_59
Build prophet model for  store_30_dept_6
Build prophet model for  store_30_dept_60

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_30_dept_67
Build prophet model for  store_30_dept_7
Build prophet model for  store_30_dept_72
Build prophet model for  store_30_dept_74
Build prophet model for  store_30_dept_79
Build prophet model for  store_30_dept_8
Build prophet model for  store_30_dept_80
Build prophet model for  store_30_dept_81
Build prophet model for  store_30_dept_82
Build prophet model for  store_30_dept_83
Build prophet model for  store_30_dept_85
Build prophet model for  store_30_dept_87
Build prophet model for  store_30_dept_9
Build prophet model for  store_30_dept_90
Build prophet model for  store_30_dept_91
Build prophet model for  store_30_dept_92
Build prophet model for  store_30_dept_93
Build prophet model for  store_30_dept_94
Build prophet model for  store_30_dept_95
Build prophet model for  store_30_dept_96
Build prophet model for  store_30_dept_97
Build prophet model for  store_30_dept_98

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_31_dept_1
Build prophet model for  store_31_dept_10

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_31_dept_11

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_31_dept_12

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_31_dept_13
Build prophet model for  store_31_dept_14
Build prophet model for  store_31_dept_16
Build prophet model for  store_31_dept_17
Build prophet model for  store_31_dept_18

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_31_dept_19
Build prophet model for  store_31_dept_2

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_31_dept_20
Build prophet model for  store_31_dept_21
Build prophet model for  store_31_dept_22
Build prophet model for  store_31_dept_23
Build prophet model for  store_31_dept_24
Build prophet model for  store_31_dept_25
Build prophet model for  store_31_dept_26
Build prophet model for  store_31_dept_27
Build prophet model for  store_31_dept_28
Build prophet model for  store_31_dept_29
Build prophet model for  store_31_dept_3

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_31_dept_30
Build prophet model for  store_31_dept_31
Build prophet model for  store_31_dept_32

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_31_dept_33
Build prophet model for  store_31_dept_34
Build prophet model for  store_31_dept_35
Build prophet model for  store_31_dept_36

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_31_dept_37

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_31_dept_38

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_31_dept_4

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_31_dept_40
Build prophet model for  store_31_dept_41
Build prophet model for  store_31_dept_42

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_31_dept_44
Build prophet model for  store_31_dept_46
Build prophet model for  store_31_dept_49
Build prophet model for  store_31_dept_5
Build prophet model for  store_31_dept_51
Skip  store_31_dept_51 due to lack of data
Build prophet model for  store_31_dept_52
Build prophet model for  store_31_dept_54
Build prophet model for  store_31_dept_55
Build prophet model for  store_31_dept_56
Build prophet model for  store_31_dept_58
Build prophet model for  store_31_dept_59
Build prophet model for  store_31_dept_6
Build prophet model for  store_31_dept_67

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_31_dept_7
Build prophet model for  store_31_dept_71

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_31_dept_72
Build prophet model for  store_31_dept_74

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_31_dept_79

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_31_dept_8

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_31_dept_80

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_31_dept_81

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_31_dept_82
Build prophet model for  store_31_dept_83
Build prophet model for  store_31_dept_85
Build prophet model for  store_31_dept_87

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.
ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_31_dept_9
Build prophet model for  store_31_dept_90
Build prophet model for  store_31_dept_91

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_31_dept_92
Build prophet model for  store_31_dept_93

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.
ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_31_dept_94
Build prophet model for  store_31_dept_95
Build prophet model for  store_31_dept_96

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_31_dept_97
Build prophet model for  store_31_dept_98
Build prophet model for  store_32_dept_1
Build prophet model for  store_32_dept_10
Build prophet model for  store_32_dept_11

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_32_dept_12

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_32_dept_13
Build prophet model for  store_32_dept_14
Build prophet model for  store_32_dept_16
Build prophet model for  store_32_dept_17
Build prophet model for  store_32_dept_18

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_32_dept_19
Build prophet model for  store_32_dept_2

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_32_dept_20
Build prophet model for  store_32_dept_21
Build prophet model for  store_32_dept_22
Build prophet model for  store_32_dept_23
Build prophet model for  store_32_dept_24
Build prophet model for  store_32_dept_25
Build prophet model for  store_32_dept_26
Build prophet model for  store_32_dept_27
Build prophet model for  store_32_dept_28
Build prophet model for  store_32_dept_29
Build prophet model for  store_32_dept_3

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_32_dept_30
Build prophet model for  store_32_dept_31
Build prophet model for  store_32_dept_32
Build prophet model for  store_32_dept_33
Build prophet model for  store_32_dept_34
Build prophet model for  store_32_dept_35
Build prophet model for  store_32_dept_36
Build prophet model for  store_32_dept_37
Build prophet model for  store_32_dept_38

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.
ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_32_dept_4

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_32_dept_40
Build prophet model for  store_32_dept_41
Build prophet model for  store_32_dept_42

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.
ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_32_dept_44
Build prophet model for  store_32_dept_46
Build prophet model for  store_32_dept_49
Build prophet model for  store_32_dept_5
Build prophet model for  store_32_dept_51
Skip  store_32_dept_51 due to lack of data
Build prophet model for  store_32_dept_52
Build prophet model for  store_32_dept_54
Build prophet model for  store_32_dept_55
Build prophet model for  store_32_dept_56
Build prophet model for  store_32_dept_58
Build prophet model for  store_32_dept_59
Build prophet model for  store_32_dept_6
Build prophet model for  store_32_dept_60
Build prophet model for  store_32_dept_67
Build prophet model for  store_32_dept_7
Build prophet model for  store_32_dept_71
Build prophet model for  store_32_dept_72

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_32_dept_74

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_32_dept_79

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_32_dept_8

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_32_dept_80

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_32_dept_81
Build prophet model for  store_32_dept_82

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_32_dept_83
Build prophet model for  store_32_dept_85
Build prophet model for  store_32_dept_87
Build prophet model for  store_32_dept_9
Build prophet model for  store_32_dept_90

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.
ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_32_dept_91

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_32_dept_92
Build prophet model for  store_32_dept_93

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_32_dept_94
Build prophet model for  store_32_dept_95
Build prophet model for  store_32_dept_96

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_32_dept_97

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_32_dept_98
Build prophet model for  store_33_dept_1
Build prophet model for  store_33_dept_10
Build prophet model for  store_33_dept_11
Build prophet model for  store_33_dept_13
Build prophet model for  store_33_dept_14
Build prophet model for  store_33_dept_16
Build prophet model for  store_33_dept_17
Build prophet model for  store_33_dept_2
Build prophet model for  store_33_dept_21
Build prophet model for  store_33_dept_26
Build prophet model for  store_33_dept_3
Build prophet model for  store_33_dept_38
Build prophet model for  store_33_dept_4
Build prophet model for  store_33_dept_40
Build prophet model for  store_33_dept_46
Build prophet model for  store_33_dept_5
Build prophet model for  store_33_dept_60
Build prophet model for  store_33_dept_67
Build prophet model for  store_33_dept_7
Build prophet model for  store_33_dept_74
Build prophet model for  store_33_dept_79
Build prophet model for  store_33_dept_8
Build prophet model for  store_33_dept_80
Build prophet model for  store_33_dept_81
Build prophet model for  store_33_dept_82
Build prophet model for  store_33_dept_83
Build prophet model for  store_33_dept_87
Build prophet model for  store_33_dept_90
Build prophet model for  store_33_dept_91
Build prophet model for  store_33_dept_92
Build prophet model for  store_33_dept_93
Build prophet model for  store_33_dept_94
Build prophet model for  store_33_dept_95
Build prophet model for  store_33_dept_96
Build prophet model for  store_33_dept_97
Build prophet model for  store_33_dept_98
Build prophet model for  store_34_dept_1
Build prophet model for  store_34_dept_10
Build prophet model for  store_34_dept_11
Build prophet model for  store_34_dept_12

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_34_dept_13
Build prophet model for  store_34_dept_14
Build prophet model for  store_34_dept_16
Build prophet model for  store_34_dept_17
Build prophet model for  store_34_dept_18
Build prophet model for  store_34_dept_2
Build prophet model for  store_34_dept_20
Build prophet model for  store_34_dept_21
Build prophet model for  store_34_dept_22
Build prophet model for  store_34_dept_23
Build prophet model for  store_34_dept_24
Build prophet model for  store_34_dept_25
Build prophet model for  store_34_dept_26
Build prophet model for  store_34_dept_27
Build prophet model for  store_34_dept_28
Build prophet model for  store_34_dept_29
Build prophet model for  store_34_dept_3
Build prophet model for  store_34_dept_30
Build prophet model for  store_34_dept_31
Build prophet model for  store_34_dept_32
Build prophet model for  store_34_dept_33
Build prophet model for  store_34_dept_34
Build prophet model for  store_34_dept_35
Build prophet model for  store_34_dept_36
Build prophet model for  store_34_dept_37
Build prophet model for  store_34_dept_38
Build prophet model for  store_34_dept_4
Build prophet model for  store_34_dept_40
Build prophet model for  store_34_dept_41
Build prophet model for  store_34_dept_42
Build prophet model for  store_34_dept_44
Build prophet model for  store_34_dept_46
Build prophet model for  store_34_dept_48
Build prophet model for  store_34_dept_49
Build prophet model for  store_34_dept_5
Build prophet model for  store_34_dept_51
Skip  store_34_dept_51 due to lack of data
Build prophet model for  store_34_dept_52
Build prophet model for  store_34_dept_54
Build prophet model for  store_34_dept_55
Build prophet model for  store_34_dept_56
Build prophet model for  store_34_dept_59
Build prophet model for  store_34_dept_6

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_34_dept_65
Build prophet model for  store_34_dept_67
Build prophet model for  store_34_dept_7
Build prophet model for  store_34_dept_71
Build prophet model for  store_34_dept_72
Build prophet model for  store_34_dept_74
Build prophet model for  store_34_dept_79

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_34_dept_8
Build prophet model for  store_34_dept_80

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_34_dept_81
Build prophet model for  store_34_dept_82
Build prophet model for  store_34_dept_83
Build prophet model for  store_34_dept_85
Build prophet model for  store_34_dept_87
Build prophet model for  store_34_dept_9
Build prophet model for  store_34_dept_90

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_34_dept_91

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_34_dept_92
Build prophet model for  store_34_dept_93
Build prophet model for  store_34_dept_94

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_34_dept_95

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_34_dept_96
Build prophet model for  store_34_dept_97
Build prophet model for  store_34_dept_98
Build prophet model for  store_35_dept_1
Build prophet model for  store_35_dept_10
Build prophet model for  store_35_dept_11
Build prophet model for  store_35_dept_12
Build prophet model for  store_35_dept_13
Build prophet model for  store_35_dept_14
Build prophet model for  store_35_dept_16
Build prophet model for  store_35_dept_17
Build prophet model for  store_35_dept_18
Build prophet model for  store_35_dept_2
Build prophet model for  store_35_dept_20
Build prophet model for  store_35_dept_21
Build prophet model for  store_35_dept_22
Build prophet model for  store_35_dept_23
Build prophet model for  store_35_dept_24
Build prophet model for  store_35_dept_25
Build prophet model for  store_35_dept_26
Build prophet model for  store_35_dept_27
Build prophet model for  store_35_dept_28
Build prophet model for  store_35_dept_29
Build prophet model for  store_35_dept_3
Build prophet model for  store_35_dept_30
Build prophet model for  store_35_dept_31
Build prophet model for  store_35_dept_32
Build prophet model for  store_35_dept_33
Build prophet model for  store_35_dept_34
Build prophet model for  store_35_dept_35
Build prophet model for  store_35_dept_36
Build prophet model for  store_35_dept_38
Build prophet model for  store_35_dept_4
Build prophet model for  store_35_dept_40
Build prophet model for  store_35_dept_41
Build prophet model for  store_35_dept_42
Build prophet model for  store_35_dept_44
Build prophet model for  store_35_dept_46
Build prophet model for  store_35_dept_5
Build prophet model for  store_35_dept_51
Build prophet model for  store_35_dept_52
Build prophet model for  store_35_dept_54
Build prophet model for  store_35_dept_55
Build prophet model for  store_35_dept_56
Build prophet model for  store_35_dept_58
Build prophet model for  store_35_dept_59
Build prophet model for  store_35_dept_6
Build prophet model for  store_35_dept_60
Build prophet model for  store_35_dept_67
Build prophet model for  store_35_dept_7
Build prophet model for  store_35_dept_71
Build prophet model for  store_35_dept_72
Build prophet model for  store_35_dept_74
Build prophet model for  store_35_dept_79
Build prophet model for  store_35_dept_8
Build prophet model for  store_35_dept_81
Build prophet model for  store_35_dept_82
Build prophet model for  store_35_dept_83
Build prophet model for  store_35_dept_85
Build prophet model for  store_35_dept_87
Build prophet model for  store_35_dept_9
Build prophet model for  store_35_dept_90
Build prophet model for  store_35_dept_91
Build prophet model for  store_35_dept_92
Build prophet model for  store_35_dept_93
Build prophet model for  store_35_dept_95
Build prophet model for  store_35_dept_97
Build prophet model for  store_36_dept_1
Build prophet model for  store_36_dept_10
Build prophet model for  store_36_dept_13
Build prophet model for  store_36_dept_14
Build prophet model for  store_36_dept_16
Build prophet model for  store_36_dept_17
Build prophet model for  store_36_dept_2
Build prophet model for  store_36_dept_21
Build prophet model for  store_36_dept_26
Build prophet model for  store_36_dept_3
Build prophet model for  store_36_dept_38
Build prophet model for  store_36_dept_4
Build prophet model for  store_36_dept_40
Build prophet model for  store_36_dept_46
Build prophet model for  store_36_dept_55
Skip  store_36_dept_55 due to lack of data
Build prophet model for  store_36_dept_59
Skip  store_36_dept_59 due to lack of data
Build prophet model for  store_36_dept_60
Build prophet model for  store_36_dept_67
Build prophet model for  store_36_dept_7
Build prophet model for  store_36_dept_74
Build prophet model for  store_36_dept_79
Build prophet model for  store_36_dept_8
Build prophet model for  store_36_dept_80
Build prophet model for  store_36_dept_81
Build prophet model for  store_36_dept_82
Build prophet model for  store_36_dept_83
Build prophet model for  store_36_dept_90
Build prophet model for  store_36_dept_91
Build prophet model for  store_36_dept_92
Build prophet model for  store_36_dept_93
Build prophet model for  store_36_dept_94
Build prophet model for  store_36_dept_95
Build prophet model for  store_36_dept_96
Build prophet model for  store_36_dept_97
Build prophet model for  store_36_dept_98
Build prophet model for  store_37_dept_1
Build prophet model for  store_37_dept_10
Build prophet model for  store_37_dept_11
Build prophet model for  store_37_dept_12
Build prophet model for  store_37_dept_13
Build prophet model for  store_37_dept_14
Build prophet model for  store_37_dept_16
Build prophet model for  store_37_dept_17
Build prophet model for  store_37_dept_18
Build prophet model for  store_37_dept_2
Build prophet model for  store_37_dept_21
Build prophet model for  store_37_dept_25
Build prophet model for  store_37_dept_28

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_37_dept_3
Build prophet model for  store_37_dept_31
Build prophet model for  store_37_dept_38
Build prophet model for  store_37_dept_4
Build prophet model for  store_37_dept_40
Build prophet model for  store_37_dept_42
Build prophet model for  store_37_dept_46
Build prophet model for  store_37_dept_5
Build prophet model for  store_37_dept_52
Build prophet model for  store_37_dept_59
Build prophet model for  store_37_dept_6
Build prophet model for  store_37_dept_60
Build prophet model for  store_37_dept_67
Build prophet model for  store_37_dept_7
Build prophet model for  store_37_dept_72
Build prophet model for  store_37_dept_74
Build prophet model for  store_37_dept_79
Build prophet model for  store_37_dept_8
Build prophet model for  store_37_dept_80
Build prophet model for  store_37_dept_81
Build prophet model for  store_37_dept_82
Build prophet model for  store_37_dept_83
Build prophet model for  store_37_dept_85
Build prophet model for  store_37_dept_87
Build prophet model for  store_37_dept_9
Build prophet model for  store_37_dept_90
Build prophet model for  store_37_dept_91
Build prophet model for  store_37_dept_92
Build prophet model for  store_37_dept_93
Build prophet model for  store_37_dept_94
Build prophet model for  store_37_dept_95
Build prophet model for  store_37_dept_96
Build prophet model for  store_37_dept_97
Build prophet model for  store_37_dept_98
Build prophet model for  store_38_dept_1
Build prophet model for  store_38_dept_10
Build prophet model for  store_38_dept_11
Build prophet model for  store_38_dept_12
Build prophet model for  store_38_dept_13
Build prophet model for  store_38_dept_14
Build prophet model for  store_38_dept_16
Build prophet model for  store_38_dept_17
Build prophet model for  store_38_dept_18
Build prophet model for  store_38_dept_2
Build prophet model for  store_38_dept_21
Build prophet model for  store_38_dept_25
Build prophet model for  store_38_dept_28
Build prophet model for  store_38_dept_3
Build prophet model for  store_38_dept_38
Build prophet model for  store_38_dept_4
Build prophet model for  store_38_dept_40
Build prophet model for  store_38_dept_42
Build prophet model for  store_38_dept_46
Build prophet model for  store_38_dept_5
Build prophet model for  store_38_dept_52
Build prophet model for  store_38_dept_59
Build prophet model for  store_38_dept_6
Build prophet model for  store_38_dept_60
Build prophet model for  store_38_dept_67
Build prophet model for  store_38_dept_7
Build prophet model for  store_38_dept_72
Build prophet model for  store_38_dept_74
Build prophet model for  store_38_dept_79
Build prophet model for  store_38_dept_8
Build prophet model for  store_38_dept_80
Build prophet model for  store_38_dept_81
Build prophet model for  store_38_dept_82
Build prophet model for  store_38_dept_83
Build prophet model for  store_38_dept_85
Build prophet model for  store_38_dept_87
Build prophet model for  store_38_dept_9
Build prophet model for  store_38_dept_90
Build prophet model for  store_38_dept_91
Build prophet model for  store_38_dept_92
Build prophet model for  store_38_dept_93
Build prophet model for  store_38_dept_94
Build prophet model for  store_38_dept_95
Build prophet model for  store_38_dept_96
Build prophet model for  store_38_dept_97
Build prophet model for  store_38_dept_98

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_39_dept_1
Build prophet model for  store_39_dept_10

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_39_dept_11
Build prophet model for  store_39_dept_12

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_39_dept_13

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_39_dept_14
Build prophet model for  store_39_dept_16
Build prophet model for  store_39_dept_17
Build prophet model for  store_39_dept_18

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_39_dept_2

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_39_dept_20
Build prophet model for  store_39_dept_21
Build prophet model for  store_39_dept_22
Build prophet model for  store_39_dept_23
Build prophet model for  store_39_dept_24
Build prophet model for  store_39_dept_25
Build prophet model for  store_39_dept_26
Build prophet model for  store_39_dept_27
Build prophet model for  store_39_dept_28
Build prophet model for  store_39_dept_29
Build prophet model for  store_39_dept_3
Build prophet model for  store_39_dept_30
Build prophet model for  store_39_dept_31
Build prophet model for  store_39_dept_32
Build prophet model for  store_39_dept_33

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_39_dept_34
Build prophet model for  store_39_dept_35
Build prophet model for  store_39_dept_36

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_39_dept_38

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_39_dept_4

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_39_dept_40

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_39_dept_41
Build prophet model for  store_39_dept_42
Build prophet model for  store_39_dept_44
Build prophet model for  store_39_dept_46

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_39_dept_49
Build prophet model for  store_39_dept_5
Build prophet model for  store_39_dept_52
Build prophet model for  store_39_dept_54
Build prophet model for  store_39_dept_55
Build prophet model for  store_39_dept_56
Build prophet model for  store_39_dept_58
Build prophet model for  store_39_dept_59
Build prophet model for  store_39_dept_6
Build prophet model for  store_39_dept_67
Build prophet model for  store_39_dept_7
Build prophet model for  store_39_dept_71
Build prophet model for  store_39_dept_72

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_39_dept_74
Build prophet model for  store_39_dept_79

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_39_dept_8

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_39_dept_80

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_39_dept_81

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_39_dept_82
Build prophet model for  store_39_dept_83
Build prophet model for  store_39_dept_85
Build prophet model for  store_39_dept_87
Build prophet model for  store_39_dept_9
Build prophet model for  store_39_dept_90

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_39_dept_91

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_39_dept_92
Build prophet model for  store_39_dept_93

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_39_dept_94
Build prophet model for  store_39_dept_95
Build prophet model for  store_39_dept_96

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_39_dept_97
Build prophet model for  store_39_dept_98
Build prophet model for  store_3_dept_1
Build prophet model for  store_3_dept_10
Build prophet model for  store_3_dept_11
Build prophet model for  store_3_dept_12
Build prophet model for  store_3_dept_13
Build prophet model for  store_3_dept_14
Build prophet model for  store_3_dept_16
Build prophet model for  store_3_dept_17
Build prophet model for  store_3_dept_18

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_3_dept_19
Build prophet model for  store_3_dept_2
Build prophet model for  store_3_dept_20
Build prophet model for  store_3_dept_21
Build prophet model for  store_3_dept_22
Build prophet model for  store_3_dept_23
Build prophet model for  store_3_dept_24
Build prophet model for  store_3_dept_25
Build prophet model for  store_3_dept_26

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_3_dept_27
Build prophet model for  store_3_dept_28
Build prophet model for  store_3_dept_29
Build prophet model for  store_3_dept_3
Build prophet model for  store_3_dept_30
Build prophet model for  store_3_dept_31
Build prophet model for  store_3_dept_32
Build prophet model for  store_3_dept_33
Build prophet model for  store_3_dept_34
Build prophet model for  store_3_dept_35
Build prophet model for  store_3_dept_36
Build prophet model for  store_3_dept_38
Build prophet model for  store_3_dept_4
Build prophet model for  store_3_dept_40
Build prophet model for  store_3_dept_41
Build prophet model for  store_3_dept_42
Build prophet model for  store_3_dept_44
Build prophet model for  store_3_dept_46
Build prophet model for  store_3_dept_5
Build prophet model for  store_3_dept_52
Build prophet model for  store_3_dept_54
Build prophet model for  store_3_dept_55
Build prophet model for  store_3_dept_56
Build prophet model for  store_3_dept_59
Build prophet model for  store_3_dept_6

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_3_dept_60
Build prophet model for  store_3_dept_67
Build prophet model for  store_3_dept_7
Build prophet model for  store_3_dept_71
Build prophet model for  store_3_dept_72
Build prophet model for  store_3_dept_74
Build prophet model for  store_3_dept_79
Build prophet model for  store_3_dept_8
Build prophet model for  store_3_dept_81
Build prophet model for  store_3_dept_82
Build prophet model for  store_3_dept_85
Build prophet model for  store_3_dept_87
Build prophet model for  store_3_dept_9
Build prophet model for  store_3_dept_90
Build prophet model for  store_3_dept_91
Build prophet model for  store_3_dept_92
Build prophet model for  store_3_dept_95
Build prophet model for  store_3_dept_96
Build prophet model for  store_3_dept_97
Build prophet model for  store_40_dept_1
Build prophet model for  store_40_dept_10
Build prophet model for  store_40_dept_11
Build prophet model for  store_40_dept_12
Build prophet model for  store_40_dept_13

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_40_dept_14
Build prophet model for  store_40_dept_16
Build prophet model for  store_40_dept_17
Build prophet model for  store_40_dept_18
Build prophet model for  store_40_dept_2
Build prophet model for  store_40_dept_20
Build prophet model for  store_40_dept_21
Build prophet model for  store_40_dept_22
Build prophet model for  store_40_dept_23
Build prophet model for  store_40_dept_24
Build prophet model for  store_40_dept_25
Build prophet model for  store_40_dept_26
Build prophet model for  store_40_dept_27
Build prophet model for  store_40_dept_28
Build prophet model for  store_40_dept_29
Build prophet model for  store_40_dept_3
Build prophet model for  store_40_dept_30
Build prophet model for  store_40_dept_31
Build prophet model for  store_40_dept_32
Build prophet model for  store_40_dept_33
Build prophet model for  store_40_dept_34
Build prophet model for  store_40_dept_35
Build prophet model for  store_40_dept_36
Build prophet model for  store_40_dept_37

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_40_dept_38
Build prophet model for  store_40_dept_4

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_40_dept_40

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_40_dept_41
Build prophet model for  store_40_dept_42
Build prophet model for  store_40_dept_44
Build prophet model for  store_40_dept_45
Build prophet model for  store_40_dept_46
Build prophet model for  store_40_dept_48
Build prophet model for  store_40_dept_5
Build prophet model for  store_40_dept_52
Build prophet model for  store_40_dept_54
Build prophet model for  store_40_dept_55
Build prophet model for  store_40_dept_56
Build prophet model for  store_40_dept_59
Build prophet model for  store_40_dept_6
Build prophet model for  store_40_dept_60
Build prophet model for  store_40_dept_67
Build prophet model for  store_40_dept_7
Build prophet model for  store_40_dept_71
Build prophet model for  store_40_dept_72

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_40_dept_74
Build prophet model for  store_40_dept_79

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_40_dept_8

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_40_dept_80
Build prophet model for  store_40_dept_81
Build prophet model for  store_40_dept_82
Build prophet model for  store_40_dept_83
Build prophet model for  store_40_dept_85
Build prophet model for  store_40_dept_87
Build prophet model for  store_40_dept_9
Build prophet model for  store_40_dept_90
Build prophet model for  store_40_dept_91
Build prophet model for  store_40_dept_92
Build prophet model for  store_40_dept_93
Build prophet model for  store_40_dept_94
Build prophet model for  store_40_dept_95
Build prophet model for  store_40_dept_96
Build prophet model for  store_40_dept_97
Build prophet model for  store_40_dept_98
Build prophet model for  store_41_dept_1

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_41_dept_10
Build prophet model for  store_41_dept_11
Build prophet model for  store_41_dept_12

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.
ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_41_dept_13
Build prophet model for  store_41_dept_14
Build prophet model for  store_41_dept_16
Build prophet model for  store_41_dept_17
Build prophet model for  store_41_dept_18

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_41_dept_2

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_41_dept_20
Build prophet model for  store_41_dept_21
Build prophet model for  store_41_dept_22
Build prophet model for  store_41_dept_23
Build prophet model for  store_41_dept_24
Build prophet model for  store_41_dept_25
Build prophet model for  store_41_dept_26
Build prophet model for  store_41_dept_27
Build prophet model for  store_41_dept_28
Build prophet model for  store_41_dept_29
Build prophet model for  store_41_dept_3

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_41_dept_30
Build prophet model for  store_41_dept_31
Build prophet model for  store_41_dept_32
Build prophet model for  store_41_dept_33
Build prophet model for  store_41_dept_34
Build prophet model for  store_41_dept_35
Build prophet model for  store_41_dept_36
Build prophet model for  store_41_dept_38
Build prophet model for  store_41_dept_4

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.
ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_41_dept_40
Build prophet model for  store_41_dept_41
Build prophet model for  store_41_dept_42

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_41_dept_44
Build prophet model for  store_41_dept_45

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_41_dept_46
Build prophet model for  store_41_dept_49
Build prophet model for  store_41_dept_5
Build prophet model for  store_41_dept_51
Build prophet model for  store_41_dept_52
Build prophet model for  store_41_dept_54
Build prophet model for  store_41_dept_55
Build prophet model for  store_41_dept_56
Build prophet model for  store_41_dept_58
Build prophet model for  store_41_dept_59
Build prophet model for  store_41_dept_6
Build prophet model for  store_41_dept_60
Build prophet model for  store_41_dept_67
Build prophet model for  store_41_dept_7
Build prophet model for  store_41_dept_71
Build prophet model for  store_41_dept_72

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_41_dept_74

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_41_dept_79
Build prophet model for  store_41_dept_8
Build prophet model for  store_41_dept_80

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.
ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_41_dept_81
Build prophet model for  store_41_dept_82
Build prophet model for  store_41_dept_83
Build prophet model for  store_41_dept_85
Build prophet model for  store_41_dept_87

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_41_dept_9
Build prophet model for  store_41_dept_90

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_41_dept_91
Build prophet model for  store_41_dept_92
Build prophet model for  store_41_dept_93

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.
ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_41_dept_94
Build prophet model for  store_41_dept_95
Build prophet model for  store_41_dept_96

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_41_dept_97
Build prophet model for  store_41_dept_98
Build prophet model for  store_42_dept_1
Build prophet model for  store_42_dept_10
Build prophet model for  store_42_dept_11
Build prophet model for  store_42_dept_12
Build prophet model for  store_42_dept_13
Build prophet model for  store_42_dept_14
Build prophet model for  store_42_dept_16
Build prophet model for  store_42_dept_17
Build prophet model for  store_42_dept_18
Build prophet model for  store_42_dept_2
Build prophet model for  store_42_dept_21
Build prophet model for  store_42_dept_25
Build prophet model for  store_42_dept_28

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_42_dept_3
Build prophet model for  store_42_dept_31
Build prophet model for  store_42_dept_32
Build prophet model for  store_42_dept_38
Build prophet model for  store_42_dept_4
Build prophet model for  store_42_dept_40
Build prophet model for  store_42_dept_42
Build prophet model for  store_42_dept_46
Build prophet model for  store_42_dept_5
Build prophet model for  store_42_dept_52
Build prophet model for  store_42_dept_59
Build prophet model for  store_42_dept_60
Build prophet model for  store_42_dept_67
Build prophet model for  store_42_dept_7
Build prophet model for  store_42_dept_74
Build prophet model for  store_42_dept_79
Build prophet model for  store_42_dept_8
Build prophet model for  store_42_dept_80
Build prophet model for  store_42_dept_81
Build prophet model for  store_42_dept_82
Build prophet model for  store_42_dept_83
Build prophet model for  store_42_dept_85
Build prophet model for  store_42_dept_9
Build prophet model for  store_42_dept_90
Build prophet model for  store_42_dept_91
Build prophet model for  store_42_dept_92
Build prophet model for  store_42_dept_93
Build prophet model for  store_42_dept_94
Build prophet model for  store_42_dept_95
Build prophet model for  store_42_dept_96
Build prophet model for  store_42_dept_97
Build prophet model for  store_42_dept_98
Build prophet model for  store_43_dept_1
Build prophet model for  store_43_dept_10
Build prophet model for  store_43_dept_11
Build prophet model for  store_43_dept_12
Build prophet model for  store_43_dept_13
Build prophet model for  store_43_dept_14
Build prophet model for  store_43_dept_16
Build prophet model for  store_43_dept_17
Build prophet model for  store_43_dept_18
Build prophet model for  store_43_dept_2
Build prophet model for  store_43_dept_21
Build prophet model for  store_43_dept_25
Build prophet model for  store_43_dept_28
Build prophet model for  store_43_dept_3
Build prophet model for  store_43_dept_38
Build prophet model for  store_43_dept_4
Build prophet model for  store_43_dept_40
Build prophet model for  store_43_dept_42
Build prophet model for  store_43_dept_46
Build prophet model for  store_43_dept_52
Build prophet model for  store_43_dept_59
Build prophet model for  store_43_dept_6
Build prophet model for  store_43_dept_60
Build prophet model for  store_43_dept_67
Build prophet model for  store_43_dept_7
Build prophet model for  store_43_dept_72
Build prophet model for  store_43_dept_74
Build prophet model for  store_43_dept_79
Build prophet model for  store_43_dept_8
Build prophet model for  store_43_dept_80
Build prophet model for  store_43_dept_81
Build prophet model for  store_43_dept_82
Build prophet model for  store_43_dept_83
Build prophet model for  store_43_dept_85
Build prophet model for  store_43_dept_9
Build prophet model for  store_43_dept_90
Build prophet model for  store_43_dept_91
Build prophet model for  store_43_dept_92
Build prophet model for  store_43_dept_93
Build prophet model for  store_43_dept_94
Build prophet model for  store_43_dept_95
Build prophet model for  store_43_dept_96
Build prophet model for  store_43_dept_97
Build prophet model for  store_43_dept_98
Build prophet model for  store_44_dept_1
Build prophet model for  store_44_dept_10
Build prophet model for  store_44_dept_11
Build prophet model for  store_44_dept_12
Build prophet model for  store_44_dept_13
Build prophet model for  store_44_dept_14
Build prophet model for  store_44_dept_16
Build prophet model for  store_44_dept_17
Build prophet model for  store_44_dept_18
Build prophet model for  store_44_dept_2
Build prophet model for  store_44_dept_21
Build prophet model for  store_44_dept_25
Build prophet model for  store_44_dept_28
Build prophet model for  store_44_dept_3
Build prophet model for  store_44_dept_38
Build prophet model for  store_44_dept_4
Build prophet model for  store_44_dept_40
Build prophet model for  store_44_dept_42
Build prophet model for  store_44_dept_46
Build prophet model for  store_44_dept_5
Build prophet model for  store_44_dept_52
Build prophet model for  store_44_dept_59
Build prophet model for  store_44_dept_6
Build prophet model for  store_44_dept_60
Build prophet model for  store_44_dept_67
Build prophet model for  store_44_dept_7
Build prophet model for  store_44_dept_72
Build prophet model for  store_44_dept_74
Build prophet model for  store_44_dept_79
Build prophet model for  store_44_dept_8
Build prophet model for  store_44_dept_80
Build prophet model for  store_44_dept_81
Build prophet model for  store_44_dept_82
Build prophet model for  store_44_dept_83
Build prophet model for  store_44_dept_87
Build prophet model for  store_44_dept_9
Build prophet model for  store_44_dept_90
Build prophet model for  store_44_dept_91
Build prophet model for  store_44_dept_92
Build prophet model for  store_44_dept_93
Build prophet model for  store_44_dept_94
Build prophet model for  store_44_dept_95
Build prophet model for  store_44_dept_96
Build prophet model for  store_44_dept_97
Build prophet model for  store_44_dept_98
Build prophet model for  store_45_dept_1
Build prophet model for  store_45_dept_10
Build prophet model for  store_45_dept_11
Build prophet model for  store_45_dept_12
Build prophet model for  store_45_dept_13
Build prophet model for  store_45_dept_14
Build prophet model for  store_45_dept_16
Build prophet model for  store_45_dept_17
Build prophet model for  store_45_dept_18
Build prophet model for  store_45_dept_19
Build prophet model for  store_45_dept_2
Build prophet model for  store_45_dept_20
Build prophet model for  store_45_dept_21
Build prophet model for  store_45_dept_22
Build prophet model for  store_45_dept_23
Build prophet model for  store_45_dept_24
Build prophet model for  store_45_dept_25
Build prophet model for  store_45_dept_26
Build prophet model for  store_45_dept_27
Build prophet model for  store_45_dept_28
Build prophet model for  store_45_dept_29
Build prophet model for  store_45_dept_3
Build prophet model for  store_45_dept_30
Build prophet model for  store_45_dept_31
Build prophet model for  store_45_dept_32
Build prophet model for  store_45_dept_33
Build prophet model for  store_45_dept_34
Build prophet model for  store_45_dept_35
Build prophet model for  store_45_dept_36
Build prophet model for  store_45_dept_38
Build prophet model for  store_45_dept_4
Build prophet model for  store_45_dept_40
Build prophet model for  store_45_dept_41
Build prophet model for  store_45_dept_42
Build prophet model for  store_45_dept_44
Build prophet model for  store_45_dept_46
Build prophet model for  store_45_dept_5
Build prophet model for  store_45_dept_52
Build prophet model for  store_45_dept_54
Build prophet model for  store_45_dept_55
Build prophet model for  store_45_dept_56
Build prophet model for  store_45_dept_58
Build prophet model for  store_45_dept_59
Build prophet model for  store_45_dept_6
Build prophet model for  store_45_dept_60
Build prophet model for  store_45_dept_67
Build prophet model for  store_45_dept_7
Build prophet model for  store_45_dept_71
Build prophet model for  store_45_dept_72
Build prophet model for  store_45_dept_74
Build prophet model for  store_45_dept_79
Build prophet model for  store_45_dept_8
Build prophet model for  store_45_dept_81
Build prophet model for  store_45_dept_82
Build prophet model for  store_45_dept_83
Build prophet model for  store_45_dept_85
Build prophet model for  store_45_dept_87
Build prophet model for  store_45_dept_9
Build prophet model for  store_45_dept_90
Build prophet model for  store_45_dept_91
Build prophet model for  store_45_dept_92
Build prophet model for  store_45_dept_93
Build prophet model for  store_45_dept_95
Build prophet model for  store_45_dept_97
Build prophet model for  store_45_dept_98
Build prophet model for  store_4_dept_1

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_4_dept_10
Build prophet model for  store_4_dept_11
Build prophet model for  store_4_dept_12

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.
ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_4_dept_13
Build prophet model for  store_4_dept_14
Build prophet model for  store_4_dept_16
Build prophet model for  store_4_dept_17
Build prophet model for  store_4_dept_18
Build prophet model for  store_4_dept_19
Build prophet model for  store_4_dept_2

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_4_dept_20
Build prophet model for  store_4_dept_21
Build prophet model for  store_4_dept_22
Build prophet model for  store_4_dept_23
Build prophet model for  store_4_dept_24
Build prophet model for  store_4_dept_25
Build prophet model for  store_4_dept_26
Build prophet model for  store_4_dept_27
Build prophet model for  store_4_dept_28
Build prophet model for  store_4_dept_29
Build prophet model for  store_4_dept_3

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_4_dept_30
Build prophet model for  store_4_dept_31
Build prophet model for  store_4_dept_32

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_4_dept_33
Build prophet model for  store_4_dept_34

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_4_dept_35
Build prophet model for  store_4_dept_36
Build prophet model for  store_4_dept_37

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.
ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_4_dept_38

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_4_dept_4

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_4_dept_40

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_4_dept_41
Build prophet model for  store_4_dept_42
Build prophet model for  store_4_dept_44
Build prophet model for  store_4_dept_46

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_4_dept_48
Build prophet model for  store_4_dept_49
Build prophet model for  store_4_dept_5
Build prophet model for  store_4_dept_52
Build prophet model for  store_4_dept_54
Build prophet model for  store_4_dept_55
Build prophet model for  store_4_dept_56
Build prophet model for  store_4_dept_58
Build prophet model for  store_4_dept_59
Build prophet model for  store_4_dept_6
Build prophet model for  store_4_dept_60
Build prophet model for  store_4_dept_67
Build prophet model for  store_4_dept_7
Build prophet model for  store_4_dept_71

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_4_dept_72
Build prophet model for  store_4_dept_74

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_4_dept_79

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_4_dept_8

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_4_dept_80

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_4_dept_81

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_4_dept_82
Build prophet model for  store_4_dept_83

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_4_dept_85

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_4_dept_87

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_4_dept_9
Build prophet model for  store_4_dept_90

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_4_dept_91

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_4_dept_92
Build prophet model for  store_4_dept_93

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_4_dept_94

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_4_dept_95
Build prophet model for  store_4_dept_96

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_4_dept_97
Build prophet model for  store_4_dept_98
Build prophet model for  store_5_dept_1
Build prophet model for  store_5_dept_10
Build prophet model for  store_5_dept_11
Build prophet model for  store_5_dept_12
Build prophet model for  store_5_dept_13
Build prophet model for  store_5_dept_14
Build prophet model for  store_5_dept_16
Build prophet model for  store_5_dept_17
Build prophet model for  store_5_dept_18
Build prophet model for  store_5_dept_2
Build prophet model for  store_5_dept_20
Build prophet model for  store_5_dept_21
Build prophet model for  store_5_dept_22
Build prophet model for  store_5_dept_23
Build prophet model for  store_5_dept_24
Build prophet model for  store_5_dept_25
Build prophet model for  store_5_dept_26
Build prophet model for  store_5_dept_27
Build prophet model for  store_5_dept_28
Build prophet model for  store_5_dept_29
Build prophet model for  store_5_dept_3
Build prophet model for  store_5_dept_30
Build prophet model for  store_5_dept_31
Build prophet model for  store_5_dept_32
Build prophet model for  store_5_dept_33
Build prophet model for  store_5_dept_34
Build prophet model for  store_5_dept_35
Build prophet model for  store_5_dept_36
Build prophet model for  store_5_dept_38
Build prophet model for  store_5_dept_4
Build prophet model for  store_5_dept_40
Build prophet model for  store_5_dept_41
Build prophet model for  store_5_dept_42
Build prophet model for  store_5_dept_44
Build prophet model for  store_5_dept_46
Build prophet model for  store_5_dept_5
Build prophet model for  store_5_dept_52
Build prophet model for  store_5_dept_54
Build prophet model for  store_5_dept_55
Build prophet model for  store_5_dept_56
Build prophet model for  store_5_dept_59
Build prophet model for  store_5_dept_6
Build prophet model for  store_5_dept_60
Build prophet model for  store_5_dept_67
Build prophet model for  store_5_dept_7
Build prophet model for  store_5_dept_71
Build prophet model for  store_5_dept_72
Build prophet model for  store_5_dept_74
Build prophet model for  store_5_dept_79
Build prophet model for  store_5_dept_8
Build prophet model for  store_5_dept_81
Build prophet model for  store_5_dept_82
Build prophet model for  store_5_dept_85
Build prophet model for  store_5_dept_87
Build prophet model for  store_5_dept_9
Build prophet model for  store_5_dept_90
Build prophet model for  store_5_dept_91
Build prophet model for  store_5_dept_92
Build prophet model for  store_5_dept_95
Build prophet model for  store_5_dept_96
Build prophet model for  store_6_dept_1

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_6_dept_10

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_6_dept_11

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_6_dept_12

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_6_dept_13
Build prophet model for  store_6_dept_14
Build prophet model for  store_6_dept_16
Build prophet model for  store_6_dept_17
Build prophet model for  store_6_dept_18

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_6_dept_19
Build prophet model for  store_6_dept_2

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_6_dept_20
Build prophet model for  store_6_dept_21
Build prophet model for  store_6_dept_22
Build prophet model for  store_6_dept_23
Build prophet model for  store_6_dept_24

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_6_dept_25
Build prophet model for  store_6_dept_26
Build prophet model for  store_6_dept_27
Build prophet model for  store_6_dept_28
Build prophet model for  store_6_dept_29

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_6_dept_3
Build prophet model for  store_6_dept_30
Build prophet model for  store_6_dept_31
Build prophet model for  store_6_dept_32

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_6_dept_33
Build prophet model for  store_6_dept_34
Build prophet model for  store_6_dept_35
Build prophet model for  store_6_dept_36

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_6_dept_37

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_6_dept_38
Build prophet model for  store_6_dept_4

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_6_dept_40

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_6_dept_41
Build prophet model for  store_6_dept_42
Build prophet model for  store_6_dept_44
Build prophet model for  store_6_dept_45
Skip  store_6_dept_45 due to lack of data
Build prophet model for  store_6_dept_46

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_6_dept_48
Build prophet model for  store_6_dept_49
Build prophet model for  store_6_dept_5
Build prophet model for  store_6_dept_52
Build prophet model for  store_6_dept_54
Build prophet model for  store_6_dept_55

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_6_dept_56
Build prophet model for  store_6_dept_58
Build prophet model for  store_6_dept_59
Build prophet model for  store_6_dept_6
Build prophet model for  store_6_dept_67
Build prophet model for  store_6_dept_7

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_6_dept_71
Build prophet model for  store_6_dept_72

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_6_dept_74

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_6_dept_79

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_6_dept_8

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_6_dept_80

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_6_dept_81

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_6_dept_82
Build prophet model for  store_6_dept_83

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_6_dept_85
Build prophet model for  store_6_dept_87

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_6_dept_9

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_6_dept_90

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_6_dept_91

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_6_dept_92
Build prophet model for  store_6_dept_93

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_6_dept_94

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_6_dept_95
Build prophet model for  store_6_dept_96

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_6_dept_97
Build prophet model for  store_6_dept_98
Build prophet model for  store_7_dept_1
Build prophet model for  store_7_dept_10
Build prophet model for  store_7_dept_11
Build prophet model for  store_7_dept_12
Build prophet model for  store_7_dept_13
Build prophet model for  store_7_dept_14
Build prophet model for  store_7_dept_16
Build prophet model for  store_7_dept_17
Build prophet model for  store_7_dept_18
Build prophet model for  store_7_dept_19
Skip  store_7_dept_19 due to lack of data
Build prophet model for  store_7_dept_2
Build prophet model for  store_7_dept_20
Build prophet model for  store_7_dept_21
Build prophet model for  store_7_dept_22
Build prophet model for  store_7_dept_23
Build prophet model for  store_7_dept_24
Build prophet model for  store_7_dept_25
Build prophet model for  store_7_dept_26
Build prophet model for  store_7_dept_27
Build prophet model for  store_7_dept_28
Build prophet model for  store_7_dept_29
Build prophet model for  store_7_dept_3
Build prophet model for  store_7_dept_30
Build prophet model for  store_7_dept_31
Build prophet model for  store_7_dept_32
Build prophet model for  store_7_dept_33
Build prophet model for  store_7_dept_34
Build prophet model for  store_7_dept_35
Build prophet model for  store_7_dept_36
Build prophet model for  store_7_dept_38
Build prophet model for  store_7_dept_4
Build prophet model for  store_7_dept_40
Build prophet model for  store_7_dept_41
Build prophet model for  store_7_dept_42
Build prophet model for  store_7_dept_44
Build prophet model for  store_7_dept_45
Build prophet model for  store_7_dept_46
Build prophet model for  store_7_dept_49
Build prophet model for  store_7_dept_5
Build prophet model for  store_7_dept_51
Skip  store_7_dept_51 due to lack of data
Build prophet model for  store_7_dept_52
Build prophet model for  store_7_dept_54
Build prophet model for  store_7_dept_55
Build prophet model for  store_7_dept_56
Build prophet model for  store_7_dept_59
Build prophet model for  store_7_dept_6
Build prophet model for  store_7_dept_60
Build prophet model for  store_7_dept_67
Build prophet model for  store_7_dept_7
Build prophet model for  store_7_dept_71
Build prophet model for  store_7_dept_72
Build prophet model for  store_7_dept_74
Build prophet model for  store_7_dept_79
Build prophet model for  store_7_dept_8
Build prophet model for  store_7_dept_81
Build prophet model for  store_7_dept_82
Build prophet model for  store_7_dept_83
Build prophet model for  store_7_dept_85
Build prophet model for  store_7_dept_87
Build prophet model for  store_7_dept_9
Build prophet model for  store_7_dept_90
Build prophet model for  store_7_dept_91
Build prophet model for  store_7_dept_92
Build prophet model for  store_7_dept_93
Build prophet model for  store_7_dept_94
Build prophet model for  store_7_dept_95
Build prophet model for  store_7_dept_96
Build prophet model for  store_7_dept_97
Build prophet model for  store_7_dept_98
Build prophet model for  store_8_dept_1
Build prophet model for  store_8_dept_10

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_8_dept_11
Build prophet model for  store_8_dept_12

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_8_dept_13
Build prophet model for  store_8_dept_14
Build prophet model for  store_8_dept_16
Build prophet model for  store_8_dept_17
Build prophet model for  store_8_dept_18
Build prophet model for  store_8_dept_19
Build prophet model for  store_8_dept_2
Build prophet model for  store_8_dept_20
Build prophet model for  store_8_dept_21
Build prophet model for  store_8_dept_22
Build prophet model for  store_8_dept_23
Build prophet model for  store_8_dept_24
Build prophet model for  store_8_dept_25
Build prophet model for  store_8_dept_26
Build prophet model for  store_8_dept_27
Build prophet model for  store_8_dept_28
Build prophet model for  store_8_dept_29
Build prophet model for  store_8_dept_3
Build prophet model for  store_8_dept_30
Build prophet model for  store_8_dept_31
Build prophet model for  store_8_dept_32
Build prophet model for  store_8_dept_33
Build prophet model for  store_8_dept_34
Build prophet model for  store_8_dept_35
Build prophet model for  store_8_dept_36
Build prophet model for  store_8_dept_37
Build prophet model for  store_8_dept_38
Build prophet model for  store_8_dept_4
Build prophet model for  store_8_dept_40
Build prophet model for  store_8_dept_41
Build prophet model for  store_8_dept_42
Build prophet model for  store_8_dept_44
Build prophet model for  store_8_dept_46
Build prophet model for  store_8_dept_49
Build prophet model for  store_8_dept_5
Build prophet model for  store_8_dept_52
Build prophet model for  store_8_dept_54
Build prophet model for  store_8_dept_55
Build prophet model for  store_8_dept_56
Build prophet model for  store_8_dept_58
Build prophet model for  store_8_dept_59
Build prophet model for  store_8_dept_6
Build prophet model for  store_8_dept_60
Build prophet model for  store_8_dept_67
Build prophet model for  store_8_dept_7
Build prophet model for  store_8_dept_71
Build prophet model for  store_8_dept_72
Build prophet model for  store_8_dept_74
Build prophet model for  store_8_dept_79

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_8_dept_8

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_8_dept_80
Build prophet model for  store_8_dept_81
Build prophet model for  store_8_dept_82
Build prophet model for  store_8_dept_83
Build prophet model for  store_8_dept_85
Build prophet model for  store_8_dept_87
Build prophet model for  store_8_dept_9
Build prophet model for  store_8_dept_90

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_8_dept_91
Build prophet model for  store_8_dept_92
Build prophet model for  store_8_dept_93

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_8_dept_94
Build prophet model for  store_8_dept_95

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_8_dept_97
Build prophet model for  store_8_dept_98
Build prophet model for  store_9_dept_1
Build prophet model for  store_9_dept_10
Build prophet model for  store_9_dept_11
Build prophet model for  store_9_dept_12
Build prophet model for  store_9_dept_13
Build prophet model for  store_9_dept_14
Build prophet model for  store_9_dept_16
Build prophet model for  store_9_dept_17
Build prophet model for  store_9_dept_18
Build prophet model for  store_9_dept_19
Build prophet model for  store_9_dept_2
Build prophet model for  store_9_dept_20
Build prophet model for  store_9_dept_21
Build prophet model for  store_9_dept_22
Build prophet model for  store_9_dept_23
Build prophet model for  store_9_dept_24
Build prophet model for  store_9_dept_25
Build prophet model for  store_9_dept_26
Build prophet model for  store_9_dept_27
Build prophet model for  store_9_dept_28
Build prophet model for  store_9_dept_29
Build prophet model for  store_9_dept_3
Build prophet model for  store_9_dept_30
Build prophet model for  store_9_dept_31
Build prophet model for  store_9_dept_32
Build prophet model for  store_9_dept_33
Build prophet model for  store_9_dept_34
Build prophet model for  store_9_dept_35
Build prophet model for  store_9_dept_36
Build prophet model for  store_9_dept_38
Build prophet model for  store_9_dept_4
Build prophet model for  store_9_dept_40
Build prophet model for  store_9_dept_41
Build prophet model for  store_9_dept_42
Build prophet model for  store_9_dept_44
Build prophet model for  store_9_dept_46
Build prophet model for  store_9_dept_5
Build prophet model for  store_9_dept_52
Build prophet model for  store_9_dept_54
Build prophet model for  store_9_dept_55
Build prophet model for  store_9_dept_56
Build prophet model for  store_9_dept_59
Build prophet model for  store_9_dept_6
Build prophet model for  store_9_dept_67
Build prophet model for  store_9_dept_7
Build prophet model for  store_9_dept_71
Build prophet model for  store_9_dept_72
Build prophet model for  store_9_dept_74
Build prophet model for  store_9_dept_79
Build prophet model for  store_9_dept_8
Build prophet model for  store_9_dept_81
Build prophet model for  store_9_dept_82
Build prophet model for  store_9_dept_85
Build prophet model for  store_9_dept_87
Build prophet model for  store_9_dept_9
Build prophet model for  store_9_dept_90
Build prophet model for  store_9_dept_91
Build prophet model for  store_9_dept_92
Build prophet model for  store_9_dept_95
Build prophet model for  store_9_dept_96
Build prophet model for  store_9_dept_97
Skip  store_9_dept_97 due to lack of data
Build prophet model for  store_12_dept_51
Skip  store_12_dept_51 due to lack of data
Build prophet model for  store_16_dept_51
Skip  store_16_dept_51 due to lack of data
Build prophet model for  store_17_dept_45
Build prophet model for  store_20_dept_48
Build prophet model for  store_21_dept_98
Build prophet model for  store_22_dept_98
Build prophet model for  store_25_dept_58
Build prophet model for  store_25_dept_80
Build prophet model for  store_26_dept_45
Skip  store_26_dept_45 due to lack of data
Build prophet model for  store_29_dept_51
Skip  store_29_dept_51 due to lack of data
Build prophet model for  store_2_dept_51
Skip  store_2_dept_51 due to lack of data
Build prophet model for  store_30_dept_31
Build prophet model for  store_34_dept_58
Skip  store_34_dept_58 due to lack of data
Build prophet model for  store_35_dept_98

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_36_dept_11
Build prophet model for  store_37_dept_56
Build prophet model for  store_38_dept_31
Build prophet model for  store_38_dept_32
Build prophet model for  store_39_dept_51
Build prophet model for  store_3_dept_51
Skip  store_3_dept_51 due to lack of data
Build prophet model for  store_42_dept_87
Build prophet model for  store_45_dept_94
Build prophet model for  store_5_dept_19
Build prophet model for  store_11_dept_45
Skip  store_11_dept_45 due to lack of data
Build prophet model for  store_12_dept_80
Build prophet model for  store_15_dept_94
Build prophet model for  store_17_dept_41
Build prophet model for  store_17_dept_98
Build prophet model for  store_18_dept_80
Build prophet model for  store_18_dept_94
Build prophet model for  store_18_dept_98
Build prophet model for  store_19_dept_51
Skip  store_19_dept_51 due to lack of data
Build prophet model for  store_23_dept_98
Build prophet model for  store_29_dept_98
Build prophet model for  store_30_dept_32
Build prophet model for  store_33_dept_18
Build prophet model for  store_35_dept_80
Build prophet model for  store_36_dept_20
Build prophet model for  store_43_dept_87
Build prophet model for  store_44_dept_85
Build prophet model for  store_4_dept_51
Skip  store_4_dept_51 due to lack of data
Build prophet model for  store_5_dept_58
Build prophet model for  store_6_dept_51
Skip  store_6_dept_51 due to lack of data
Build prophet model for  store_15_dept_51
Skip  store_15_dept_51 due to lack of data
Build prophet model for  store_21_dept_94
Build prophet model for  store_22_dept_45
Skip  store_22_dept_45 due to lack of data
Build prophet model for  store_23_dept_80
Build prophet model for  store_24_dept_45
Skip  store_24_dept_45 due to lack of data
Build prophet model for  store_26_dept_51
Skip  store_26_dept_51 due to lack of data
Build prophet model for  store_33_dept_59
Skip  store_33_dept_59 due to lack of data
Build prophet model for  store_39_dept_45
Build prophet model for  store_40_dept_51
Skip  store_40_dept_51 due to lack of data
Build prophet model for  store_43_dept_32
Build prophet model for  store_44_dept_23
Build prophet model for  store_44_dept_32
Build prophet model for  store_45_dept_80
Build prophet model for  store_16_dept_45

INFO:prophet:n_changepoints greater than number of observations. Using 24.

Build prophet model for  store_18_dept_51
Skip  store_18_dept_51 due to lack of data
Build prophet model for  store_19_dept_45
Skip  store_19_dept_45 due to lack of data
Build prophet model for  store_30_dept_41
Build prophet model for  store_33_dept_25
Build prophet model for  store_34_dept_45
Skip  store_34_dept_45 due to lack of data
Build prophet model for  store_38_dept_56
Build prophet model for  store_43_dept_31
Build prophet model for  store_43_dept_56
Build prophet model for  store_44_dept_55
Skip  store_44_dept_55 due to lack of data
Build prophet model for  store_4_dept_45
Build prophet model for  store_5_dept_45
Skip  store_5_dept_45 due to lack of data
Build prophet model for  store_7_dept_58
Build prophet model for  store_30_dept_56
Build prophet model for  store_33_dept_20
Build prophet model for  store_36_dept_25
Build prophet model for  store_42_dept_56
Build prophet model for  store_44_dept_31
Build prophet model for  store_44_dept_56
Build prophet model for  store_4_dept_78
Skip  store_4_dept_78 due to lack of data
Build prophet model for  store_11_dept_19
Build prophet model for  store_22_dept_19
Build prophet model for  store_22_dept_94
Build prophet model for  store_24_dept_78
Skip  store_24_dept_78 due to lack of data
Build prophet model for  store_29_dept_94
Build prophet model for  store_32_dept_45
Build prophet model for  store_33_dept_9
Build prophet model for  store_37_dept_55
Skip  store_37_dept_55 due to lack of data
Build prophet model for  store_45_dept_51
Skip  store_45_dept_51 due to lack of data
Build prophet model for  store_18_dept_45
Skip  store_18_dept_45 due to lack of data
Build prophet model for  store_18_dept_78
Skip  store_18_dept_78 due to lack of data
Build prophet model for  store_25_dept_94
Build prophet model for  store_33_dept_55
Build prophet model for  store_5_dept_94
Build prophet model for  store_15_dept_98
Build prophet model for  store_17_dept_94
Build prophet model for  store_29_dept_19
Build prophet model for  store_33_dept_12
Build prophet model for  store_36_dept_18
Build prophet model for  store_7_dept_80
Build prophet model for  store_16_dept_80
Build prophet model for  store_21_dept_51
Skip  store_21_dept_51 due to lack of data
Build prophet model for  store_34_dept_19
Build prophet model for  store_18_dept_50
Build prophet model for  store_20_dept_45
Skip  store_20_dept_45 due to lack of data
Build prophet model for  store_21_dept_60
Build prophet model for  store_29_dept_80
Build prophet model for  store_3_dept_47
Skip  store_3_dept_47 due to lack of data
Build prophet model for  store_14_dept_47
Skip  store_14_dept_47 due to lack of data
Build prophet model for  store_31_dept_60

ERROR:cmdstanpy:Chain [1] error: code '1' Operation not permitted
WARNING:prophet.models:Optimization terminated abnormally. Falling back to Newton.

Build prophet model for  store_37_dept_20
Build prophet model for  store_43_dept_5
Build prophet model for  store_21_dept_80
Build prophet model for  store_24_dept_51
Skip  store_24_dept_51 due to lack of data
Build prophet model for  store_27_dept_60
Build prophet model for  store_36_dept_9
Build prophet model for  store_38_dept_26
Build prophet model for  store_41_dept_47
Skip  store_41_dept_47 due to lack of data
Build prophet model for  store_24_dept_60
Build prophet model for  store_25_dept_45
Skip  store_25_dept_45 due to lack of data
Build prophet model for  store_29_dept_60
Build prophet model for  store_33_dept_42
Build prophet model for  store_36_dept_42
Build prophet model for  store_36_dept_12
Build prophet model for  store_38_dept_20

INFO:prophet:n_changepoints greater than number of observations. Using 11.

Build prophet model for  store_20_dept_51
Skip  store_20_dept_51 due to lack of data
Build prophet model for  store_27_dept_47
Build prophet model for  store_35_dept_94

INFO:prophet:n_changepoints greater than number of observations. Using 15.

Build prophet model for  store_9_dept_47
Skip  store_9_dept_47 due to lack of data
Build prophet model for  store_20_dept_47
Build prophet model for  store_28_dept_45
Skip  store_28_dept_45 due to lack of data
Build prophet model for  store_3_dept_45
Skip  store_3_dept_45 due to lack of data
Build prophet model for  store_42_dept_20
Build prophet model for  store_5_dept_97
Build prophet model for  store_15_dept_47
Skip  store_15_dept_47 due to lack of data
Build prophet model for  store_30_dept_20
Build prophet model for  store_38_dept_44
Build prophet model for  store_43_dept_20
Build prophet model for  store_6_dept_78
Skip  store_6_dept_78 due to lack of data
Build prophet model for  store_9_dept_94
Build prophet model for  store_15_dept_45
Skip  store_15_dept_45 due to lack of data
Build prophet model for  store_25_dept_19
Skip  store_25_dept_19 due to lack of data
Build prophet model for  store_25_dept_47
Skip  store_25_dept_47 due to lack of data
Build prophet model for  store_2_dept_60

INFO:prophet:n_changepoints greater than number of observations. Using 20.

Build prophet model for  store_31_dept_45
Skip  store_31_dept_45 due to lack of data
Build prophet model for  store_36_dept_52
Skip  store_36_dept_52 due to lack of data
Build prophet model for  store_8_dept_45
Skip  store_8_dept_45 due to lack of data
Build prophet model for  store_10_dept_47

INFO:prophet:n_changepoints greater than number of observations. Using 22.

Build prophet model for  store_27_dept_45
Skip  store_27_dept_45 due to lack of data
Build prophet model for  store_35_dept_47
Build prophet model for  store_38_dept_23
Build prophet model for  store_9_dept_45
Skip  store_9_dept_45 due to lack of data
Build prophet model for  store_30_dept_26
Skip  store_30_dept_26 due to lack of data
Build prophet model for  store_36_dept_41
Skip  store_36_dept_41 due to lack of data
Build prophet model for  store_1_dept_96

INFO:prophet:n_changepoints greater than number of observations. Using 8.

Build prophet model for  store_42_dept_44

INFO:prophet:n_changepoints greater than number of observations. Using 5.

Build prophet model for  store_43_dept_26
Build prophet model for  store_33_dept_52
Build prophet model for  store_36_dept_87
Build prophet model for  store_43_dept_44
Skip  store_43_dept_44 due to lack of data
Build prophet model for  store_22_dept_49

INFO:prophet:n_changepoints greater than number of observations. Using 19.

Build prophet model for  store_28_dept_47
Skip  store_28_dept_47 due to lack of data
Build prophet model for  store_45_dept_78
Skip  store_45_dept_78 due to lack of data
Build prophet model for  store_18_dept_60

INFO:prophet:n_changepoints greater than number of observations. Using 17.

Build prophet model for  store_31_dept_47
Skip  store_31_dept_47 due to lack of data
Build prophet model for  store_39_dept_19
Build prophet model for  store_4_dept_47
Skip  store_4_dept_47 due to lack of data
Build prophet model for  store_20_dept_19
Build prophet model for  store_21_dept_45
Skip  store_21_dept_45 due to lack of data
Build prophet model for  store_29_dept_47
Skip  store_29_dept_47 due to lack of data
Build prophet model for  store_3_dept_94

INFO:prophet:n_changepoints greater than number of observations. Using 12.

Build prophet model for  store_45_dept_45

INFO:prophet:n_changepoints greater than number of observations. Using 4.

Build prophet model for  store_38_dept_34
Build prophet model for  store_36_dept_5
Build prophet model for  store_22_dept_48
Skip  store_22_dept_48 due to lack of data
Build prophet model for  store_33_dept_6
Skip  store_33_dept_6 due to lack of data
Build prophet model for  store_35_dept_49

INFO:prophet:n_changepoints greater than number of observations. Using 8.

Build prophet model for  store_36_dept_6

INFO:prophet:n_changepoints greater than number of observations. Using 17.

Build prophet model for  store_38_dept_33
Build prophet model for  store_8_dept_47
Skip  store_8_dept_47 due to lack of data
Build prophet model for  store_17_dept_49

INFO:prophet:n_changepoints greater than number of observations. Using 10.

Build prophet model for  store_2_dept_47
Skip  store_2_dept_47 due to lack of data
Build prophet model for  store_10_dept_78
Skip  store_10_dept_78 due to lack of data
Build prophet model for  store_1_dept_47
Build prophet model for  store_16_dept_60

INFO:prophet:n_changepoints greater than number of observations. Using 7.

Build prophet model for  store_16_dept_58
Build prophet model for  store_16_dept_98

INFO:prophet:n_changepoints greater than number of observations. Using 10.

Build prophet model for  store_33_dept_44
Build prophet model for  store_34_dept_60
Build prophet model for  store_40_dept_58

INFO:prophet:n_changepoints greater than number of observations. Using 11.

Build prophet model for  store_11_dept_47
Build prophet model for  store_25_dept_60
Build prophet model for  store_29_dept_45
Skip  store_29_dept_45 due to lack of data
Build prophet model for  store_3_dept_98
Skip  store_3_dept_98 due to lack of data
Build prophet model for  store_12_dept_47
Skip  store_12_dept_47 due to lack of data
Build prophet model for  store_21_dept_47

INFO:prophet:n_changepoints greater than number of observations. Using 8.
INFO:prophet:n_changepoints greater than number of observations. Using 7.

Build prophet model for  store_26_dept_47

INFO:prophet:n_changepoints greater than number of observations. Using 6.

Build prophet model for  store_7_dept_47
Build prophet model for  store_33_dept_56
Skip  store_33_dept_56 due to lack of data
Build prophet model for  store_41_dept_19
Build prophet model for  store_9_dept_60

INFO:prophet:n_changepoints greater than number of observations. Using 3.

Build prophet model for  store_23_dept_48
Skip  store_23_dept_48 due to lack of data
Build prophet model for  store_40_dept_47
Build prophet model for  store_15_dept_60

INFO:prophet:n_changepoints greater than number of observations. Using 15.

Build prophet model for  store_30_dept_34
Skip  store_30_dept_34 due to lack of data
Build prophet model for  store_42_dept_72

INFO:prophet:n_changepoints greater than number of observations. Using 0.

Build prophet model for  store_38_dept_24
Skip  store_38_dept_24 due to lack of data
Build prophet model for  store_44_dept_44
Build prophet model for  store_44_dept_20
Build prophet model for  store_33_dept_22

INFO:prophet:n_changepoints greater than number of observations. Using 7.

Build prophet model for  store_6_dept_47

INFO:prophet:n_changepoints greater than number of observations. Using 7.

Build prophet model for  store_16_dept_47
Build prophet model for  store_36_dept_56
Skip  store_36_dept_56 due to lack of data
Build prophet model for  store_12_dept_49

INFO:prophet:n_changepoints greater than number of observations. Using 11.

Build prophet model for  store_19_dept_47
Build prophet model for  store_23_dept_60

INFO:prophet:n_changepoints greater than number of observations. Using 5.

Build prophet model for  store_28_dept_51
Skip  store_28_dept_51 due to lack of data
Build prophet model for  store_37_dept_44
Build prophet model for  store_6_dept_60
Build prophet model for  store_26_dept_60
Build prophet model for  store_41_dept_48

INFO:prophet:n_changepoints greater than number of observations. Using 6.

Build prophet model for  store_18_dept_47

INFO:prophet:n_changepoints greater than number of observations. Using 20.

Build prophet model for  store_39_dept_99

INFO:prophet:n_changepoints greater than number of observations. Using 3.

Build prophet model for  store_45_dept_47
Build prophet model for  store_25_dept_51
Skip  store_25_dept_51 due to lack of data
Build prophet model for  store_37_dept_23
Build prophet model for  store_42_dept_23
Build prophet model for  store_7_dept_48
Build prophet model for  store_30_dept_23
Build prophet model for  store_31_dept_99
Build prophet model for  store_33_dept_41
Build prophet model for  store_37_dept_27
Build prophet model for  store_42_dept_27
Build prophet model for  store_43_dept_23
Skip  store_43_dept_23 due to lack of data
Build prophet model for  store_30_dept_27
Skip  store_30_dept_27 due to lack of data
Build prophet model for  store_38_dept_27
Build prophet model for  store_11_dept_60

INFO:prophet:n_changepoints greater than number of observations. Using 24.

Build prophet model for  store_11_dept_99

INFO:prophet:n_changepoints greater than number of observations. Using 17.

Build prophet model for  store_19_dept_19
Skip  store_19_dept_19 due to lack of data
Build prophet model for  store_34_dept_99
Build prophet model for  store_23_dept_47
Skip  store_23_dept_47 due to lack of data
Build prophet model for  store_39_dept_60

INFO:prophet:n_changepoints greater than number of observations. Using 5.

Build prophet model for  store_9_dept_80

INFO:prophet:n_changepoints greater than number of observations. Using 21.

Build prophet model for  store_27_dept_51
Skip  store_27_dept_51 due to lack of data
Build prophet model for  store_43_dept_27
Skip  store_43_dept_27 due to lack of data
Build prophet model for  store_2_dept_99

INFO:prophet:n_changepoints greater than number of observations. Using 7.

Build prophet model for  store_37_dept_24
Build prophet model for  store_44_dept_27

INFO:prophet:n_changepoints greater than number of observations. Using 22.

Build prophet model for  store_20_dept_99

INFO:prophet:n_changepoints greater than number of observations. Using 21.

Build prophet model for  store_4_dept_99

INFO:prophet:n_changepoints greater than number of observations. Using 19.

Build prophet model for  store_6_dept_99

INFO:prophet:n_changepoints greater than number of observations. Using 22.

Build prophet model for  store_14_dept_99

INFO:prophet:n_changepoints greater than number of observations. Using 0.

Build prophet model for  store_38_dept_29
Build prophet model for  store_37_dept_26
Skip  store_37_dept_26 due to lack of data
Build prophet model for  store_12_dept_78
Skip  store_12_dept_78 due to lack of data
Build prophet model for  store_45_dept_49
Build prophet model for  store_13_dept_78
Skip  store_13_dept_78 due to lack of data
Build prophet model for  store_40_dept_49
Build prophet model for  store_5_dept_47
Skip  store_5_dept_47 due to lack of data
Build prophet model for  store_9_dept_49

INFO:prophet:n_changepoints greater than number of observations. Using 15.

Build prophet model for  store_23_dept_78
Skip  store_23_dept_78 due to lack of data
Build prophet model for  store_30_dept_22
Build prophet model for  store_30_dept_24
Skip  store_30_dept_24 due to lack of data
Build prophet model for  store_9_dept_48

INFO:prophet:n_changepoints greater than number of observations. Using 21.

Build prophet model for  store_13_dept_99
Build prophet model for  store_15_dept_78
Skip  store_15_dept_78 due to lack of data
Build prophet model for  store_16_dept_49

INFO:prophet:n_changepoints greater than number of observations. Using 17.

Build prophet model for  store_1_dept_99
Build prophet model for  store_29_dept_49

INFO:prophet:n_changepoints greater than number of observations. Using 19.

Build prophet model for  store_32_dept_99

INFO:prophet:n_changepoints greater than number of observations. Using 19.

Build prophet model for  store_36_dept_31

INFO:prophet:n_changepoints greater than number of observations. Using 19.

Build prophet model for  store_19_dept_78
Skip  store_19_dept_78 due to lack of data
Build prophet model for  store_19_dept_99

INFO:prophet:n_changepoints greater than number of observations. Using 18.

Build prophet model for  store_24_dept_99

INFO:prophet:n_changepoints greater than number of observations. Using 18.

Build prophet model for  store_26_dept_99

INFO:prophet:n_changepoints greater than number of observations. Using 17.

Build prophet model for  store_27_dept_99

INFO:prophet:n_changepoints greater than number of observations. Using 19.

Build prophet model for  store_28_dept_99

INFO:prophet:n_changepoints greater than number of observations. Using 20.

Build prophet model for  store_41_dept_99

INFO:prophet:n_changepoints greater than number of observations. Using 11.

Build prophet model for  store_37_dept_22

INFO:prophet:n_changepoints greater than number of observations. Using 16.

Build prophet model for  store_40_dept_99

INFO:prophet:n_changepoints greater than number of observations. Using 15.

Build prophet model for  store_8_dept_99

INFO:prophet:n_changepoints greater than number of observations. Using 15.

Build prophet model for  store_33_dept_31

INFO:prophet:n_changepoints greater than number of observations. Using 0.

Build prophet model for  store_36_dept_23
Skip  store_36_dept_23 due to lack of data
Build prophet model for  store_33_dept_33
Skip  store_33_dept_33 due to lack of data
Build prophet model for  store_33_dept_24
Skip  store_33_dept_24 due to lack of data
Build prophet model for  store_37_dept_33
Build prophet model for  store_27_dept_78
Skip  store_27_dept_78 due to lack of data
Build prophet model for  store_26_dept_48

INFO:prophet:n_changepoints greater than number of observations. Using 3.

Build prophet model for  store_26_dept_50
Skip  store_26_dept_50 due to lack of data
Build prophet model for  store_32_dept_78
Skip  store_32_dept_78 due to lack of data
Build prophet model for  store_36_dept_44

INFO:prophet:n_changepoints greater than number of observations. Using 11.

Build prophet model for  store_19_dept_48
Skip  store_19_dept_48 due to lack of data
Build prophet model for  store_5_dept_98
Build prophet model for  store_8_dept_78
Skip  store_8_dept_78 due to lack of data
Build prophet model for  store_16_dept_83
Build prophet model for  store_16_dept_93
Build prophet model for  store_5_dept_49
Build prophet model for  store_3_dept_49

INFO:prophet:n_changepoints greater than number of observations. Using 10.

Build prophet model for  store_3_dept_80

INFO:prophet:n_changepoints greater than number of observations. Using 15.

Build prophet model for  store_43_dept_22

INFO:prophet:n_changepoints greater than number of observations. Using 19.

Build prophet model for  store_9_dept_98
Skip  store_9_dept_98 due to lack of data
Build prophet model for  store_38_dept_22

INFO:prophet:n_changepoints greater than number of observations. Using 1.

Build prophet model for  store_32_dept_48
Skip  store_32_dept_48 due to lack of data
Build prophet model for  store_39_dept_47
Skip  store_39_dept_47 due to lack of data
Build prophet model for  store_35_dept_19

INFO:prophet:n_changepoints greater than number of observations. Using 6.

Build prophet model for  store_43_dept_33
Skip  store_43_dept_33 due to lack of data
Build prophet model for  store_32_dept_47

INFO:prophet:n_changepoints greater than number of observations. Using 9.

Build prophet model for  store_42_dept_22

INFO:prophet:n_changepoints greater than number of observations. Using 3.

Build prophet model for  store_44_dept_22
Skip  store_44_dept_22 due to lack of data
Build prophet model for  store_22_dept_47

INFO:prophet:n_changepoints greater than number of observations. Using 17.

Build prophet model for  store_16_dept_48

INFO:prophet:n_changepoints greater than number of observations. Using 23.

Build prophet model for  store_17_dept_78
Skip  store_17_dept_78 due to lack of data
Build prophet model for  store_17_dept_96

INFO:prophet:n_changepoints greater than number of observations. Using 3.

Build prophet model for  store_30_dept_49
Skip  store_30_dept_49 due to lack of data
Build prophet model for  store_34_dept_47

INFO:prophet:n_changepoints greater than number of observations. Using 21.

Build prophet model for  store_37_dept_49

INFO:prophet:n_changepoints greater than number of observations. Using 11.

Build prophet model for  store_18_dept_96

INFO:prophet:n_changepoints greater than number of observations. Using 1.

Build prophet model for  store_24_dept_47
Skip  store_24_dept_47 due to lack of data
Build prophet model for  store_28_dept_78
Skip  store_28_dept_78 due to lack of data
Build prophet model for  store_2_dept_78
Skip  store_2_dept_78 due to lack of data
Build prophet model for  store_13_dept_47

INFO:prophet:n_changepoints greater than number of observations. Using 2.

Build prophet model for  store_31_dept_78
Skip  store_31_dept_78 due to lack of data
Build prophet model for  store_36_dept_22

INFO:prophet:n_changepoints greater than number of observations. Using 0.

Build prophet model for  store_20_dept_77

INFO:prophet:n_changepoints greater than number of observations. Using 11.

Build prophet model for  store_38_dept_49

INFO:prophet:n_changepoints greater than number of observations. Using 15.

Build prophet model for  store_4_dept_77
Skip  store_4_dept_77 due to lack of data
Build prophet model for  store_30_dept_55
Skip  store_30_dept_55 due to lack of data
Build prophet model for  store_42_dept_49

INFO:prophet:n_changepoints greater than number of observations. Using 12.

Build prophet model for  store_45_dept_77
Skip  store_45_dept_77 due to lack of data
Build prophet model for  store_27_dept_77
Skip  store_27_dept_77 due to lack of data
Build prophet model for  store_33_dept_32

INFO:prophet:n_changepoints greater than number of observations. Using 12.

Build prophet model for  store_37_dept_32

INFO:prophet:n_changepoints greater than number of observations. Using 2.

Build prophet model for  store_14_dept_96

INFO:prophet:n_changepoints greater than number of observations. Using 2.

Build prophet model for  store_20_dept_96

INFO:prophet:n_changepoints greater than number of observations. Using 10.

Build prophet model for  store_44_dept_26

INFO:prophet:n_changepoints greater than number of observations. Using 6.

Build prophet model for  store_33_dept_23

INFO:prophet:n_changepoints greater than number of observations. Using 5.

Build prophet model for  store_44_dept_24

INFO:prophet:n_changepoints greater than number of observations. Using 5.

Build prophet model for  store_42_dept_71
Fail to train  store_42_dept_71 : Dataframe has less than 2 non-NaN rows.
Build prophet model for  store_43_dept_49

INFO:prophet:n_changepoints greater than number of observations. Using 2.

Build prophet model for  store_12_dept_96

INFO:prophet:n_changepoints greater than number of observations. Using 1.

Build prophet model for  store_36_dept_72

INFO:prophet:n_changepoints greater than number of observations. Using 4.

Build prophet model for  store_44_dept_33

INFO:prophet:n_changepoints greater than number of observations. Using 1.

Build prophet model for  store_17_dept_47
Skip  store_17_dept_47 due to lack of data
Build prophet model for  store_35_dept_96

INFO:prophet:n_changepoints greater than number of observations. Using 0.
INFO:prophet:n_changepoints greater than number of observations. Using 1.

Build prophet model for  store_30_dept_99
Build prophet model for  store_36_dept_32
Build prophet model for  store_25_dept_48
Skip  store_25_dept_48 due to lack of data
Build prophet model for  store_42_dept_26
Skip  store_42_dept_26 due to lack of data
Build prophet model for  store_44_dept_49
Skip  store_44_dept_49 due to lack of data
Build prophet model for  store_22_dept_96
Skip  store_22_dept_96 due to lack of data
Build prophet model for  store_38_dept_55
Skip  store_38_dept_55 due to lack of data
Build prophet model for  store_19_dept_39
Skip  store_19_dept_39 due to lack of data

KeyError: 'rmse'

In [21]:
print(
    f"Prophet Model Results:\nMAE: {mean_mae:.2f} | RMSE: {mean_rmse:.2f} | WAPE: {ovr_wampe:.2f}%"
)

NameError: name 'mean_mae' is not defined