In [12]:
!git clone https://github.com/hoangquan1503/Walmart_sales_forecasting.git

fatal: destination path 'Walmart_sales_forecasting' already exists and is not an empty directory.

In [13]:
%cd Walmart_sales_forecasting

/content/Walmart_sales_forecasting/Walmart_sales_forecasting

In [14]:
# Install dependencies as needed:
# pip install kagglehub[pandas-datasets]
import numpy as np
import pandas as pd
import kagglehub
from kagglehub import KaggleDatasetAdapter


# Set the path to the file you'd like to load


# Load the latest version
train = kagglehub.load_dataset(
  KaggleDatasetAdapter.PANDAS,
  "aslanahmedov/walmart-sales-forecast",
  "train.csv",
)
stores = kagglehub.load_dataset(
  KaggleDatasetAdapter.PANDAS,
  "aslanahmedov/walmart-sales-forecast",
  "stores.csv",
)
features = kagglehub.load_dataset(
  KaggleDatasetAdapter.PANDAS,
  "aslanahmedov/walmart-sales-forecast",
  "features.csv",
)

df = train.merge(stores, on='Store').merge(features, on=['Store', 'Date'])

print("First 5 records:", df.head())

/tmp/ipykernel_2462/3181991320.py:13: DeprecationWarning: Use dataset_load() instead of load_dataset(). load_dataset() will be removed in a future version.
  train = kagglehub.load_dataset(

Using Colab cache for faster access to the 'walmart-sales-forecast' dataset.

/tmp/ipykernel_2462/3181991320.py:18: DeprecationWarning: Use dataset_load() instead of load_dataset(). load_dataset() will be removed in a future version.
  stores = kagglehub.load_dataset(

Using Colab cache for faster access to the 'walmart-sales-forecast' dataset.

/tmp/ipykernel_2462/3181991320.py:23: DeprecationWarning: Use dataset_load() instead of load_dataset(). load_dataset() will be removed in a future version.
  features = kagglehub.load_dataset(

Using Colab cache for faster access to the 'walmart-sales-forecast' dataset.
First 5 records:    Store  Dept        Date  Weekly_Sales  IsHoliday_x Type    Size  \
0      1     1  2010-02-05      24924.50        False    A  151315
1      1     1  2010-02-12      46039.49         True    A  151315
2      1     1  2010-02-19      41595.55        False    A  151315
3      1     1  2010-02-26      19403.54        False    A  151315
4      1     1  2010-03-05      21827.90        False    A  151315

   Temperature  Fuel_Price  MarkDown1  MarkDown2  MarkDown3  MarkDown4  \
0        42.31       2.572        NaN        NaN        NaN        NaN
1        38.51       2.548        NaN        NaN        NaN        NaN
2        39.93       2.514        NaN        NaN        NaN        NaN
3        46.63       2.561        NaN        NaN        NaN        NaN
4        46.50       2.625        NaN        NaN        NaN        NaN

   MarkDown5         CPI  Unemployment  IsHoliday_y
0        NaN  211.096358         8.106        False
1        NaN  211.242170         8.106         True
2        NaN  211.289143         8.106        False
3        NaN  211.319643         8.106        False
4        NaN  211.350143         8.106        False

In [15]:
df['Date'] = pd.to_datetime(df['Date'])
df['Date']

0        2010-02-05
1        2010-02-12
2        2010-02-19
3        2010-02-26
4        2010-03-05
            ...
421565   2012-09-28
421566   2012-10-05
421567   2012-10-12
421568   2012-10-19
421569   2012-10-26
Name: Date, Length: 421570, dtype: datetime64[ns]

In [16]:
from src.data_cleaning import check_missing_value, fill_missing_promote

check_missing_value(df)

              counts     ratio
Store              0  0.000000
Dept               0  0.000000
Date               0  0.000000
Weekly_Sales       0  0.000000
IsHoliday_x        0  0.000000
Type               0  0.000000
Size               0  0.000000
Temperature        0  0.000000
Fuel_Price         0  0.000000
MarkDown1     270889  0.642572
MarkDown2     310322  0.736110
MarkDown3     284479  0.674808
MarkDown4     286603  0.679847
MarkDown5     270138  0.640790
CPI                0  0.000000
Unemployment       0  0.000000
IsHoliday_y        0  0.000000

In [17]:
markdown = ['MarkDown1', 'MarkDown2', 'MarkDown3', 'MarkDown4', 'MarkDown5']
fill_missing_promote(df, markdown)

TypeError: fill_missing_promote() takes 1 positional argument but 2 were given